### ISSUE TITLE
grid mask in grid longname

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1079]
The grid mask got dropped from the grid long name - put it back.

**Comment by ekluzek** [comment]
I'm just going to open this up to point out that that the fix put in still doesn't allow the previous settings of grid in config_compsets.xml for CLM. So the CLM workaround in bugzilla bug 2418 is still required (at least with cime5.2.0-alpha.23). I think that's OK though, because we aren't using this feature for CLM50 yet. I'm sure we will be though and we might need to address something when we do. But, we might as well not worry about it for now.
