### ISSUE TITLE
WW3 does not create input_data_list

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#1168]
Components provide their input data requirements in a `Buildconf/<model>.input_data_list` file, however, ww3 does not seem to produce this file so the model's data needs cannot be checked by `check_input_data`.

**Comment by billsacks** [comment]
@gold2718 and @mvertens - is this still an issue? If so, does it need to be resolved for cesm2?

**Comment by mvertens** [comment]
Yes - this is a critical issue and I have moved it to the CESM milestones
as such. I have a fix for this for ww3 and am testing it now and will
hopefully get a new trunk tag made shortly.

**Comment by mvertens** [comment]
This is critical for the CESM2 release because users will not be able to automatically download this file from the inputdata repository without check_input_data capability - so they will not be able to get the CESM2 scientifically supported configurations working out of the box.

This is a CESM2 bug ONLY.

**Comment by mvertens** [comment]
This has been resolved by the ww3 tag: 
`https://svn-ccsm-models.cgd.ucar.edu/ww3/trunk_tags/ww3_170514`
