### ISSUE TITLE
Unable to rerun a test

### ISSUE THREAD

**Issue by apcraig** [ESMCI/cime#1215]
With the latest trunk, I'm unable to rerun a test.  When I try to do so, I get the traceback below.  This seems to be because the local TestStatus file does not have write permission.  Only the TestStatus file seems to have this permission issue.  If I chmod u+w to TestStatus, the test reruns fine and the TestStatus permissions are not reset.

Exception during run:
[Errno 13] Permission denied: '/glade/p/work/tcraig/cime.nuopc/scripts/SMS.T31_g37_rx1.A.yellowstone_intel.nBa01/TestStatus'
Traceback (most recent call last):
  File "/glade/p/work/tcraig/cime.nuopc/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 137, in run
    self._test_status.set_status(RUN_PHASE, TEST_PEND_STATUS)
  File "/glade/p/work/tcraig/cime.nuopc/scripts/Tools/../../scripts/lib/CIME/test_status.py", line 129, in __exit__
    self.flush()
  File "/glade/p/work/tcraig/cime.nuopc/scripts/Tools/../../scripts/lib/CIME/test_status.py", line 225, in flush
    with open(self._filename, "w") as fd:
IOError: [Errno 13] Permission denied: '/glade/p/work/tcraig/cime.nuopc/scripts/SMS.T31_g37_rx1.A.yellowstone_intel.nBa01/TestStatus'

**Comment by jedwards4b** [comment]
This happens if the first run went wrong.  Manually change permissions on the TestStatus file
before submitting the second job.

**Comment by apcraig** [comment]
That seems pretty inconvenient.  I'm not sure what setting the write bit on that file is trying to accomplish, but there must be another way.  How about a couple of env flags or something, one that sets whether the last test went right or wrong, the other whether the user wants the submit to fail if the last test went wrong.  During development, if I have to keep flipping that permission bit, it's going to be very frustrating.

**Comment by jedwards4b** [comment]
There has been an ongoing problem with detecting and handling submit failures in tests.  This is the solution we have been able to come up with and I agree that it's not ideal - you are invited  to submit a working alternative if you can come up with one.

**Comment by apcraig** [comment]
Are the requirements or a few use cases defined somewhere?

**Comment by jedwards4b** [comment]
See #1006 and #1136

**Comment by billsacks** [comment]
I agree with @apcraig that the current behavior is unintuitive and likely to trip people up. 

@jedwards4b , I read through the issue and PR that you referenced, but it's still unclear to me why it is necessary to change the permissions of the TestStatus file - that need isn't discussed anywhere, as far as I can tell.

Is the whole issue here the ERR test? If so, the most intuitive solution to me would be to design the ERR test itself so that it will fail if any of its jobs fail to run, e.g., as @fischer-ncar suggests here https://github.com/ESMCI/cime/issues/416#issuecomment-279089122 . I'd prefer a solution like that rather than the current solution that involves embedding test-specific logic in the production code.

**Comment by jedwards4b** [comment]
The problem is not specifically the ERR test, it's just the one that most easily demonstrates the problem.   Since @jgfouca implemented this solution, I would like to invite him to the discussion.

**Comment by gold2718** [comment]
Can someone post a reproducer? I resubmit failed tests all the time without looking at file permissions.

**Comment by jgfouca** [comment]
The TestStatus file is set to read-only if an exception occurs during the batch submission. This is so that, if the exception occurred after the job is submitted, the submitted job can't change the TestStatus to PASS.

Admittedly, this solution is very hacky; I was thinking that this type of error would be quite rare but apparently that isn't the case.

**Comment by jgfouca** [comment]
Maybe we could treat the batch submission as it's own phase?

PASS Test SUBMIT

**Comment by apcraig** [comment]
A quick short term improvement would be for the submission script to check the permission of TestStatus and to NOT submit if it's read only and to produce a reasonable error message.  Then at least the user could fix this quickly (ie chmod the file) and continue working.  That would help a lot.  Longer term, I agree that this deserves further review.
