### ISSUE TITLE
More discussion on sphinx/rst workflow

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#1338]
I missed this when it was discussed in #1088 but @rljacob said

> One thing I noticed is that even if I do a fresh checkout and make no changes, "make html" will change files such that git notices. Mostly "doctree" but some "html". Maybe that's a sphinx version difference? Anyway the only solution is to "git add ." everything under "build" so even more churn.

I have two comments:

1. doctree does not need to be in the repo, it should be in `.gitignore`
1. It looks to me that the html changes are just sphinx adding a line "Created using Sphinx X.Y.Z" to the page

For example, I checked out the `gh-pages` branch and ran `make clean; make html`.

```
$ git diff *.html
diff --git a/doc/build/html/build_cpl/index.html b/doc/build/html/build_cpl/index.html
index 98802df..a119960 100644
--- a/doc/build/html/build_cpl/index.html
+++ b/doc/build/html/build_cpl/index.html
@@ -132,7 +132,7 @@
     </div>
     <div class="footer" role="contentinfo">
         &#169; Copyright 2017, Mariana Vertenstein, Rob Jacob, Jim Edwards, Jim Foucar, Alice Bertini.
-      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.5.2.
+      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.5.1.
     </div>
   </body>
 </html>
\ No newline at end of file
diff --git a/doc/build/html/build_cpl/introduction.html b/doc/build/html/build_cpl/introduction.html
index d19c8be..92b3771 100644
--- a/doc/build/html/build_cpl/introduction.html
+++ b/doc/build/html/build_cpl/introduction.html
@@ -118,7 +118,7 @@
     </div>
     <div class="footer" role="contentinfo">
         &#169; Copyright 2017, Mariana Vertenstein, Rob Jacob, Jim Edwards, Jim Foucar, Alice Bertini.
-      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.5.2.
+      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.5.1.
     </div>
   </body>
 </html>
\ No newline at end of file
```
(and on and on for 700 lines)

So for (2), I think we need to all agree to use the same version of Sphinx. This is easier said than done, though -- I use conda to manage my python packages and it appears that I can choose between 1.5.1 and 1.5.4; I don't know what @mvertens is using, but it looks like she has 1.5.2 installed.

**Comment by mnlevy1981** [comment]
FYI,

```
$ pip install sphinx==1.5.2
```

inside a new conda environment is all it for me to get the correct version installed.

```
$ make clean
$ make html
$ git status
On branch levy/runoff-doc
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   build/html/searchindex.js

no changes added to commit (use "git add" and/or "git commit -a")
```

Not sure why `searchindex.js` changes, but that's the only difference I see

**Comment by jhkennedy** [comment]
The setup of CIME's `gh-pages` branch is a little a-typical for github. 

Typically, you'd have the `gh-pages` setup as an *orphaned* branch, so the only thing in the branch is the HTML (no "code" at all). 

In the rest of the branches (the "code" branches), you'd have the `doc` directory where you could use sphinx to generate the documentation, with all of the *generated* documentation ignored so it doesn't go into the repository. 

When a new thing is ready to be merged to `master`, the integrator (whoever actually does the merge) would make the documentation and copy the new generated HTML into the `gh-pages` branch (usually that branch lives in a separate checkout so it's just `cp` to that checkouts directory and committing it there) 

That way, the documentation is up to date with `master` always, devs can edit the documentation as the develop (something that could be enforced by the integrators in order to satisfy a PR), all the generated stuff stays out of the code branches (no churn) and you don't see it in PRs, and checkouts of the `gh-pages` branch are small (only HTML and static elements). 

-------------

The way CIME has it set up currently is that the `gh-pages` branch is a full fledge branch of the code branches, and looks to be the only current dev. branch with the `doc` directory in it. This means that to update the documentation there are extra unnecessary steps:

1) checking out the `gh-pages` branch to work on the documentation
2) only editing `*.rst` files in the that branch and being careful with documentation commits
3) having to merge `master` in to use any autodocs type features 

And, more importantly, the documentation changes are inherently separated from the corresponding code changes, which makes keeping the documentation up to date very hard. 

--------

It might be beneficial to adopt a more typical documentation structure for CIME, and I think that's what @mvertens was getting at in #1088 

It'd be relatively easy to do: 

- [ ] move the doc directory, and any other needed changes, from `gh-pages` into `master`
- [ ] generate the documentation, and a `.gitignore` for all the generated docs 
- [ ] delete the `gh-pages` branch entirely
- [ ] create a new orphaned `gh-pages` branch in a separate checkout
- [ ] copy in the generated website and commit it to the `gh-pages` branch

**Comment by rljacob** [comment]
Thanks for pointing this out.  @mvertens and @bertinia , we should do this.    I don't think the discussion in #1088 was aware of this issue.

**Comment by bertinia** [comment]
I'll set this up this weekend. @bjsmith2014 is actively working on the gh-pages branch
today and tomorrow and I'll wait for his updates before making the switch.

**Comment by jhkennedy** [comment]
@bertinia I'm also happy to help if you have questions.

**Comment by mvertens** [comment]
I am actively working on a gh-pages branch for the porting documentation -
so please wait for me as well.

**Comment by bertinia** [comment]
@jhkennedy - I've moved the gh-pages branch doc dir into my local master and updated the .gitignore to add this:

    # Ignore doc/build/doctrees
    ##doc/build/doctrees 
    # ignore for the merge to master and orphaning of the gh-pages branch
    doc/build
  
and updated my upstream fork of the cime master.

Do I now issue a PR to merge this back into the ESMCI/cime master or continue to create
an orphan branch on my fork before the PR?

**Comment by jhkennedy** [comment]
@bertinia, when working in a fork you'd have to issue a PR for fork/master to cime/master, and then when you have the orphaned branch set up, issue a PR for fork/gh-pages to cime/gh-pages. 

Whoever integrates the merge will want to delete the current cime/gh-pages branch before merging the gh-pages PR. 

*Note: This likely will cause people's local version of gh-pages to get comply out of sync, so after the above is done, and looks good, everyone should delete their local copy of gh-pages and checkout a fresh copy.*

**Comment by jgfouca** [comment]
Unintentional closure due to ACME merge.
