### ISSUE TITLE
Change user_nl_* to YAML

### ISSUE THREAD

**Issue by erichlf** [ESMCI/cime#1422]
After some discussion in other issues relating to user_nl_* syntax, I think it would be a good idea to switch to a standard such as YAML.

**Comment by gold2718** [comment]
The namelist is a uniquely Fortran construct so to me, using Fortran syntax and semantics makes sense (at least as long as all of our top-level models are written in Fortran).
What is your perceived advantage to YAML?
What is your plan for backwards compatibility (user_nl_* files exist in hundreds or thousands of existing scripts)?

**Comment by mvertens** [comment]
@goldy We already discussed this at the CIME today.

First, user_nl_xxx does not support purely fortran namelists. It supports
the cime input - which is not namelist based and also the seq_maps.rc in
the driver - also not namelist based. But it must support at the least
fortran namelist capability.

Second, we decided to defer conversion for YAML, etc for the time being -
since the issues of backwards compatibility do become a real concern.

**Comment by gold2718** [comment]
@mvertens, Thanks for the update (I had a code review at the same time as the CIME call). I also realized that CISM inputs are not Fortran (right?).
When we do decide on a generalization for Fortran namelist input, I think we should keep user_nl_* for Fortran and move to an alternate name (e.g., user_input_*) so we can eventually deprecate the user_nl_* files.

**Comment by erichlf** [comment]
My reasoning for YAML is because it is a set standard that people aren't going to argue over once it is decided.

**Comment by gold2718** [comment]
@erichlf, I think you underestimate our ability to argue :)
In my suggestion above, a new user_input_* file would be in YAML and would take precedence over a user_nl_* file (so you shouldn't use both). I think that provides a non-disruptive path forward.
