### ISSUE TITLE
z level syntax stripped from atmosphere grid

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#1459]
Using the old (v1) config_grids.xml, one could use `z` to specify the number of levels, e.g., `ne30z60_ne30`. However, in v2, this information is stripped and not passed to the component buildcpp for processing.

**Comment by mvertens** [comment]
The problem is that the grid longname is not created correctly 
If you issue the following command:

`./create_newcase --case testzlev --compset FKESSLER --res ne16z32_ne16 --run-unsupported`

you get the grid longname

`a%ne16np4_l%null_oi%null_r%null_g%null_w%null_m%gx3v7`

which is incorrect - the atm grid should be ne16np4z32 not ne16np4
