### ISSUE TITLE
Remove manage_testslists

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#1512]
This is a CESM only issue.
We need have all of the testslists migrated to the new schema - and then simply remove the manage_testlist script. This should wait until after the CESM2 release. The main culprit is probably CLM - but this needs to be confirmed. CESM liaisons can help with this if need be.

**Comment by ekluzek** [comment]
We do want to move to the new schema for CLM as there is additional functionality we'd like to tap into. And we do need to redo our testlists as we need to redo all the compsets as well.

So is the idea that you edit the XML in the test lists directly rather than using the tool? I thought the tool was developed so that we didn't have to touch the XML directly because there were problems when people did that?

**Comment by billsacks** [comment]
> So is the idea that you edit the XML in the test lists directly rather than using the tool?

Yes. Or create a macro / snippet in your editor of choice to facilitate this.

> I thought the tool was developed so that we didn't have to touch the XML directly because there were problems when people did that?

The new schema makes it easier to edit the xml directly.

For more on this, see the long email thread with subject "you can help speed up testing", Oct 4-6, 2016. This is too long of a thread to easily copy to this github issue, but @ekluzek you were on it, and if others want to see it, I can try to copy relevant bits here.

The short summary is: The manage tool relied on being able to convert back and forth between xml and a plain text format. But this got hard to support as we started adding options like wallclock time, memleak tolerance, etc. Much of the benefit of using xml is being able to support extra options like this; we couldn't come up with a good way to support this in the flat text format that was both (1) human readable / writeable, and (2) machine parseable (in order to regenerate an xml file). Even if we could, this introduces a maintenance burden because we have to support two formats and a tool to translate between the two formats. That said, I don't object to having a manage tool... it's just that nobody had the time to write one.

**Comment by fischer-ncar** [comment]
Should we push forward on removing manage_testlist for the CESM2 release, since the release is being
delayed?

**Comment by billsacks** [comment]
Not until all components have converted their testlist format, which hasn't happened yet.

**Comment by ekluzek** [comment]
@billsacks what components haven't converted yet?

**Comment by gold2718** [comment]
CAM for one.
-- @gold2718, reporting from the stone age

**Comment by billsacks** [comment]
@ekluzek CLM hasn't converted yet either

**Comment by mnlevy1981** [comment]
@billsacks -- I'm not sure what the plans for POP's testlist are, and @alperaltuntas is on vacation this week and next week. I, personally, use `manage_testlists` (I assume you mean that rather than`manage_externals`?) but (a) don't update my CIME version that frequently (I'll probably make a `cesm2_0_beta09` sandbox when it's available and then not move forward until a POP trunk tag requires a CIME update), and (b) don't add / remove tests that frequently. So don't feel like you need to keep `manage_testlists` around for me but I can't really speak for anyone else.

**Comment by billsacks** [comment]
@mnlevy1981 sounds good. Yes, I meant `manage_testlists`. I don't think there's a reason to remove it until it's really no longer used, so it should probably be kept until POP migrates to a new format.

**Comment by billsacks** [comment]
@mnlevy1981 and @alperaltuntas - can manage_testlists be removed now?
