### ISSUE TITLE
Matches appear to differ depending on whether in config_compsets or config_component

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#1617]
I get different matches for the following dependent on whether it is in config_compsets or config_component.  (I've indicated the two lines which MATCH).  When this is in config_compsets, I get the first match.  When it is in config_components, I get the last.

    <entry id="SSTICE_DATA_FILENAME">
      <values>
        <value compset="DOCN%DOM" grid="a%T31.*_oi%T31"         >$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_48x96_clim_c050526.nc</value>
        <value compset="DOCN%DOM" grid="a%1.9x2.5.*_oi%1.9x2.5" >$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_1.9x2.5_clim_c061031.nc</value>
        **MATCH** <value compset="DOCN%DOM" grid="a%0.9x1.25.*_oi%0.9x1.25">$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_0.9x1.25_clim_c040926.nc</value>
      <value compset="DOCN%DOM" grid="a%0.47x0.63.*_oi%0.47x0.63">$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_0.47x0.63_clim_c061106.nc</value>
      <value compset="DOCN%DOM" grid="a%0.23x0.31.*_oi%0.23x0.31">$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_0.23x0.31_clim_c110526.nc</value>
      <value compset="(AMIP_|HIST_|20TR_|5505_|PIPD_|%TSCH)" grid=".+"  >$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_1x1_1850_2012_c130411.nc</value>
      <value compset="(AMIP_|HIST_|20TR_|5505_|PIPD_|%TSCH)" grid="a%T31.*_oi%T31">$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_48x96_1850_2012_c130411.nc</value>
      <value compset="(AMIP_|HIST_|20TR_|5505_|PIPD_|%TSCH)" grid="a%1.9x2.5.*_oi%1.9x2.5">$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_1.9x2.5_1850_2012_c130411.nc</value>
      **MATCH**<value compset="(AMIP_|HIST_|20TR_|5505_|PIPD_|%TSCH)" grid="a%0.9x1.25.*_oi%0.9x1.25">$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_0.9x1.25_1850_2012_c130411.nc</value>
      <value compset="(AMIP_|HIST_|20TR_|5505_|PIPD_|%TSCH)" grid="a%0.47x0.63.*_oi%0.47x0.63">$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_0.47x0.63_1850_2012_c130411.nc</value>
      <value compset="(AMIP_|HIST_|20TR_|5505_|PIPD_|%TSCH)" grid="a%0.23x0.31.*_oi%0.23x0.31">$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_0.23x0.31_1850_2012_c130411.nc</value>
      <value compset="1850_" grid=".+"                          >$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_1x1_clim_pi_c101029.nc</value>
      <value compset="1850_" grid="a%T31.*_oi%T31"              >$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_48x96_clim_pi_c101028.nc</value>
      <value compset="1850_" grid="a%1.9x2.5.*_oi%1.9x2.5"      >$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_1.9x2.5_clim_pi_c101028.nc</value>
      <value compset="1850_" grid="a%0.9x1.25.*_oi%0.9x1.25"    >$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_0.9x1.25_clim_pi_c101028.nc</value>
      <value compset="1850_" grid="a%0.47x0.63.*_oi%0.47x0.63"  >$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_0.47x0.63_clim_pi_c101028.nc</value>
      <value compset="1850_" grid="a%0.23x0.31.*_oi%0.23x0.31"  >$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_0.23x0.31_clim_pi_c101028.nc</value>
        <value compset="FRC1_" grid="a%1.9x2.5.*_oi%1.9x2.5"    >$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_1.9x2.5_1850_2015_c160510.nc</value>
        <value compset="SDYN_" grid="a%1.9x2.5.*_oi%1.9x2.5"    >$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_1.9x2.5_1850_2015_c160510.nc</value>
        <value compset="SDYN_" grid="a%0.9x1.25.*_oi%0.9x1.25"  >$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_0.9x1.25_1850_2015_c160510.nc</value>
        <value compset="SDYN_" grid="a%0.47x0.63.*_oi%0.47x0.63">$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_0.45x0.63_1850_2015_c160510.nc</value>
        <value compset="SDYN_" grid="a%0.23x0.31.*_oi%0.23x0.31">$DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_0.23x0.31_1850_2015_c160510.nc</value>
      </values>
    </entry>

**Comment by jedwards4b** [comment]
There are two instances of function _get_value_match: one in class entry_id.py and another in component.py so the instance in config_component.xml is processed using component.py while the
instance in config_compset.py is processed using entry_id.py  - I think that the one in entry_id.py is needed by namelist stuff, and the solution might be to have the config_compset code use the one in component.py.    One way to do that would be to introduce a new class which both compsets.py and component.py inherit from and which contains only this function.

**Comment by jedwards4b** [comment]
The issue is in get_compset_var_settings in compsets.py - it uses a generic entry_id object in order
to access the _get_value_match function, it needs to use the one in component.py - i'll leave it as an exercise to figure out how.

**Comment by mvertens** [comment]
We cannot do that for backwards compatibility purposes. Unfortunately,
namelist matches that parse the new python based namelist_definition_xxx.py
file pick the first match that is found when multiple matches are found
(this is done to be consistent with all of the perl based functionality) -
whereas the component.py entry-id match picks the latest (again for
backwards compatibility). This is unfortunate and confusing and should be
addressed post-release. But having just one new class that picks only one
way will potentially cause a lot of refactoring to occur and will need
extensive testing - neither of which we should take on before the release.
So a shorter term fix needs to be implemented.

**Comment by mvertens** [comment]
So in thinking about this some more I think we do have a critical issue on our hands that will require us to do the following:

The namelist_definition.xml match inherits from entry_id  and the entry_id match - use the first match in case case of a tie. 

However, the component.py also inherits from entry_id - but has its own _get_value_match that picks (unfortunately) the ***last*** best match. 

I think we need to proceed forwards in two steps.

First, **We need to change component.py to have the first best match - otherwise we have a complete nightmare on our hands.**  That could easily be done my making the following change in component.py - change

```
                # take the *last* best match
                elif match_count >= match_max:

```
to 
```
                # take the *first* best match
                elif match_count >= match_max:
```  

This might break things in both ACME and CESM prognostic config_components.py - so when this is fixed we need to carefully do testing.

I agree with Jim that we should only be inheriting from one function. That would be the next step.

**Comment by mvertens** [comment]
In looking at CIME - there are only a few places that a careful analysis and restructuring needs to be done:

```
in the driver  config_component_cesm.xml and  config_component_acme.xml
   CCSM_BGC, ATM_NCPL, ROF_NCPL, CPL_EPBAL, CPLSEQ_OPTION, BUDGETS

in the docn config_component.xml
    SSTICE_DATA_FILENAME, SSTICE_GRID_FILENAME
```

**Comment by mvertens** [comment]
@gold2718 had a great idea for a better approach:

Add a new, optional, attribute to the config_component.xml <values> tag as follows

<values match="last"> will pick the last best match
<values match="first"> will pick the first best match

In component.py, the parsing can be done to have a  default value as  "last" to be backwards compatible - but the order of matching is now clear - and can be changed if desired. Therefore there is no ambiguity and everything is backwards compatible.

I solved the compsets problem creating a Component object in compsets.py rather than a EntryId object to parse the EntryId fields. Since the Component object now has the ability to parse the "first" and "last" attribute - this can also be changed - but the default behavior will be maintained as before.

So this will require no changes to the config_component.xml files. However, I am putting in <values match="last"> at this point where there is ambiguity as part of what will be my PR.

Having this attribute will permit moving forwards with a general solution that involves code reuse.
