### ISSUE TITLE
Coupling/run length check to prevent restarts from failing

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#1707]
When a run length is specified that is shorter than the longest coupling interval, necessary restart files are not written.  A check should be put into the driver to abort if this is the case.

**Comment by billsacks** [comment]
Thanks for raising this issue, @cacraigucar . I think that the actual requirement is that the restart interval needs to be an integer multiple of all components' coupling intervals.

**Comment by jgfouca** [comment]
I looked closely at implementing this in CIME python and I've decided that it doesn't really make sense to put it there. All of the logic for determining run length (decifering all the various START and STOP options) currently lives in the fortran, so the logic for this enhancement probably belongs there too.

**Comment by jedwards4b** [comment]
@billsacks It seems that the esmf timemanager handles setting the restart time to an interval that makes sense for the components. I tried to fool it and didn't manage.

**Comment by billsacks** [comment]
@jedwards4b I'm not sure I understand your comment. I'm pretty sure I've run into situations where I try to write a restart file in the middle of some component's coupling interval and the first I learn of the problem is when I go to restart and the rpointer file is missing for that component (or something like that). Would it help if I came up with a test case that demonstrates this? Or am I misunderstanding your comment?

**Comment by jedwards4b** [comment]
A test case would help a lot.   Thanks

**Comment by billsacks** [comment]
@jedwards4b okay, here's a test case that fails from cesm alpha10e with cime at master:

ERS_Ln48.f10_f10_musgs.I1850Clm50Sp.cheyenne_intel

This does a restart one time step into the second day. Because of the rof coupling interval, this results in an empty rpointer.rof file. The initial run finishes successfully, but the restart run fails with:

```
7:forrtl: severe (24): end-of-file during read, unit 99, file /glade2/scratch2/sacks/ERS_Ln48.f10_f10_musgs.I1850Clm50Sp.cheyenne_intel.20180502_161541_3fpwdl/run/./rpointer.rof
7:Image              PC                Routine            Line        Source
7:cesm.exe           00000000015A80CC  Unknown               Unknown  Unknown
7:cesm.exe           00000000015E1A05  Unknown               Unknown  Unknown
7:cesm.exe           0000000000C9B682  rtmrestfile_mp_rt         265  RtmRestFile.F90
7:cesm.exe           0000000000C6828D  rtmmod_mp_rtmini_         340  RtmMod.F90
7:cesm.exe           0000000000C645D6  rof_comp_mct_mp_r         193  rof_comp_mct.F90
7:cesm.exe           0000000000427018  component_mod_mp_         267  component_mod.F90
7:cesm.exe           000000000041675D  cime_comp_mod_mp_        1186  cime_comp_mod.F90
7:cesm.exe           0000000000424242  MAIN__                     92  cime_driver.F90
```

(Side note: This compset uses an SGLC because the compset was defined incorrectly. This has been fixed to use CISM in more recent versions of CTSM. If you use a more recent version of CTSM, you may see the error in GLC rather than ROF.)
