### ISSUE TITLE
PIO_NUMTASKS is getting reset

### ISSUE THREAD

**Issue by amametjanov** [ESMCI/cime#1711]
Setting env_run.xml's PIO_STRIDE to default -99 and PIO_NUMTASKS to 64 resets both PIO_STRIDE and PIO_NUMTASKS to different default values at run-time.

XML comments:
```
    <entry id="PIO_STRIDE">
      <desc>
     stride in compute comm of io tasks for each component, if this value is -99 it will 
     be computed based on PIO_NUMTASKS and number of compute tasks
    </desc>
```

but instead of 64, PIO_NUMTASKS is getting reset to 8 or 16 depending on the number of component's MPI tasks.

Note that setting PIO_STRIDE to a specific value and leaving PIO_NUMTASKS at default -99 works as expected: PIO_NUMTASKS is set to NTASKS / PIO_STRIDE.

**Comment by jayeshkrishna** [comment]
Looks like the issue is in shr_pio_mod.F90:shr_pio_read_component_namelist() where the stride is set to default (if stride = -99) without checking if pio_numiotasks are valid,
```
if(pio_stride== -99) pio_stride = pio_default_stride
```
If pio_numiotasks is valid the code should try to compute stride from it.
A related issue is that shr_pio_read_component_namelist() is doing the job of function shr_pio_namelist_set() that already has logic to reset stride and numiotasks to valid
values.

**Comment by jedwards4b** [comment]
I think that this is the change you need:
```

**Comment by jedwards4b** [comment]
```

**Comment by jedwards4b** [comment]
```

**Comment by jedwards4b** [comment]
I think this is the change you need to make:
```
diff --git a/src/share/util/shr_pio_mod.F90 b/src/share/util/shr_pio_mod.F90
index 27894e9..b3ed425 100644
--- a/src/share/util/shr_pio_mod.F90
+++ b/src/share/util/shr_pio_mod.F90
@@ -545,7 +545,13 @@ contains
 
           call shr_pio_getiotypefromname(pio_typename, pio_iotype, pio_default_iotype)
        end if
-       if(pio_stride== -99) pio_stride = pio_default_stride
+       if(pio_stride== -99) then
+          if (pio_numiotasks > 0) then
+             pio_stride = npes/pio_numiotasks
+          else
+             pio_stride = pio_default_stride
+          endif
+       endif
```
