### ISSUE TITLE
How does parallelism in create_test work?

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#1723]
On `yellowstone`, it was very easy to request a dedicated compute node on which to run `create_test` and I never really worried about the internal parallelization of the tool. On `cheyenne`, though, the best I can do is request half a node in the share queue... so if I'm running `create_test` twice (say with two different compilers), then it's very likely that the two jobs will be running in parallel on the same node and I'd like to make sure the two jobs play nicely with each other. How do I best set `--parallel-jobs` and `--proc-pool` to run 14 tests on 18 tasks while allowing the BUILD steps to use multiple threads? More generally, what if I want to run `N` tests on `M` tasks for `N<M`, `N=M`, or `N>M`?

**Comment by mnlevy1981** [comment]
I should also add that part of my confusion stems from the fact that `create_test` is noticeably slower on cheyenne than it is on yellowstone. This may be due to differences in compiler versions, but my first thought is that it's related to the default settings of these parallelization options. Again, the Yellowstone script runs on a dedicated node with 16 cores while the Cheyenne script runs on 18 cores on a node with 36 cores (and a system that allows other users to request the remaining 18)

****

Yellowstone, Intel 15.0.3
```
test-scheduler took 2667.841398 seconds
```

vs

Cheyenne, Intel 17.0.1
```
test-scheduler took 5128.54976177 seconds
```

****

Yellowstone, GNU 5.2.0
```
test-scheduler took 1206.2003181 seconds
```

vs

Cheyenne, GNU 6.3.0
```
test-scheduler took 1786.64098692 seconds
```

**Comment by jgfouca** [comment]
Hi @mnlevy1981,

There are many levels of parallelism, so I can understand the confusion.

--parallel-jobs controls task-level parallelism (IE how many test-cases can be in flight at the same time)
--proc-pool controls the size of the processor pool that create_test will use.

In order for a phase of an individual test to begin, there must be an available thread (1 spare thread in parallel-jobs) and there must be available processors in the proc-pool. The number of proc-pool procs needed for a phase will depend on the job and phase. Most of the lightweight phases (create_newcase, xml, case_setup) all just need one proc. The build phases typically request 4 procs because there's some interval build-level parallelism going on. The number of cores used for building is NOT under the control of create_test.

It sounds like the settings you want are:
--parallel-jobs=4 # somewhat of a guess, don't want to slam the machine too much
--proc-pool=18
