### ISSUE TITLE
Cryptic error message for typo in compset name

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#1871]
From a cesm2_0_alpha07 sandbox that uses cime5.3.0-alpha.33

```
[yslogin6:/glade/scratch/sacks/cesm_code/cesm2_0_alpha07/cime/scripts]$ ./create_newcase --case test_cism_0906b --compset TG --res f09_g16
Did not find a compset match for longname TG
Compset forcing is
ERROR: No variable CONFIG_ATM_FILE found in case
```

The first line of the error message is understandable, but the next two lines make no sense. For such a common error, we should have a more user-friendly error message. e.g., can the next two lines simply be removed from the output in this case?

**Comment by rljacob** [comment]
That first line should say "Did not find longname compset match for alias TG"

**Comment by jedwards4b** [comment]
@rljacob that would be incorrect - what is meant is "did not find an alias for TG assuming it is a compset longname"   Now I can tell that TG is not a compset longname but I haven't figured out a general rule to determine what is a compset longname.  That's why there is currently no error at this point in the code.
