### ISSUE TITLE
more robust method of determining when rof2ocn_fmapname (and maybe others) can be set to idmap

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#1908]
Currently, the setting of `rof2ocn_fmapname` needs to be set to a non "idmap" value if the "flood_present" flag is on. The flood_present flag is actually set by the ocean component at run time - so this is a bit of a chicken and egg problem. The flood_present flag is used in `prep_ocn_mod.F90` and then expects a valid value of `rof2ocn_fmapname`. For a data ocean model - flood_present can always be assumed to be false and so `rof2ocn_fmapname` can be "idmap". However, this is not necessarily the case for a prognostic ocean. A more robust method needs to be determined in order to determine if setting `rof2ocn_fmapname` = "idmap" is problematic.

@billsacks provided the following: Ideally, we'd have some data-driven list of mapping pairs that are optional (i.e., needed in some configuration but not in others).

**Comment by billsacks** [comment]
This is also an issue for glc2ice_rmapname and glc2ocn_rmapname: These are also needed in some configurations but not in others. I personally feel it's too much to ask the cime scripts to have the necessary logic to determine when these are needed, since their need is based on some non-trivial logic in glc. So I'm fine with the checks of these mapnames being deferred to runtime, as is currently the case. But ideally the listing of these as optional (i.e., not to be checked in the scripts) should be done in an xml file, rather than the current hard-coded list (`ignore_idmaps`) in `src/drivers/mct/cime_config/buildnml`.

**Comment by billsacks** [comment]
@mvertens and @jedwards4b I just noticed that config_grids.xml already has a required_gridmaps section, which appears to be checked in grids.py: `_get_gridmaps_v2` (although it generates a warning rather than aborting with an error there). A naive glance makes it look like the grid-checking code that @mvertens recently added to the drv buildnml is serving essentially the same purpose as this existing code in grids.py. If that's true:

- Should one of them be removed?

- It looks like there is at least the start of a data-driven mechanism for listing the required mapping files in place via the required_gridmaps xml entries... is that usable for the purposes of this issue?

**Comment by mvertens** [comment]
@sacks - I agree with you. I was aware of this when I implemented my check
- but I only wanted to change one thing. I do think we can remove the check
in grids.py - but I think we need to think carefully if there is some check
that is missing from what I did. @jedwards4b - thoughts?

**Comment by billsacks** [comment]
What is the rationale for having the check in the drv buildnml rather than in grids.py? I'm not arguing one way or the other, I just want to understand it, particularly if the plan is to remove the existing infrastructure for grid checking (e.g., the required_gridmaps section of xml) and build new infrastructure that serves a similar purpose.

**Comment by jedwards4b** [comment]
So to the question of where does this code belong - is it independent of driver?  If so I think it belongs in grids.py, otherwise in the driver buildnml.    This is only a warning in grids.py because at the time I put this code in place there were many such cases and we didn't want to fail them.

**Comment by mvertens** [comment]
I think that the check should be done in the driver buildnml since the user
can change mapping files at run time - and there could possibly be future
checks that might be done that might be more detailed than the ones
currently implemented.

**Comment by billsacks** [comment]
> I think that the check should be done in the driver buildnml since the user
> can change mapping files at run time - and there could possibly be future
> checks that might be done that might be more detailed than the ones
> currently implemented.

Okay, thanks.
