### ISSUE TITLE
--skip-preview-namelist on batch systems 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1935]
The syntax of --skip-preview-namelist option needs to be modified to work on pbs batch systems.

**Comment by jedwards4b** [comment]
@jgfouca I'd like your thoughts on this, it doesn't work on pbs systems and I don't see a way to make a command line argument to case.run work in general.

**Comment by jgfouca** [comment]
Just to fill-in others, the Jims discussed this and discovered:

```
qsub -v args_for_caserun='--skip-preview-namelist' ...
```

then, in case.run, we'd need to pass os.environ["args_for_caserun"] into parse_args instead of sys.argv

We'll probably need a new config_batch entry for all batch types that will tell us how to pass environment variables to the submit script.

**Comment by jgfouca** [comment]
@jedwards4b I think I have a rough idea how to do this if you want to reassign to me.
