### ISSUE TITLE
Make new STA test type

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2012]
make SystemTests/sta.py

it will test short-term archiving while running.

**Comment by billsacks** [comment]
Can you describe how this will differ from other tests that cover the short-term archiver, like ERR and IRT?

**Comment by mfdeakin-sandia** [comment]
First note this will be E3SM specific, since only E3SM supports running the archiver while the model is running.
The difference is we want to standardize testing the archiver while the E3SM model is running, with the --last-date option to ensure things don't move around before we're ready. I don't actually think we need a new test type for this though - adding a test to scripts_regression_tests.py for E3SM will likely be more straightforward and correct.

**Comment by billsacks** [comment]
@mfdeakin-sandia okay thanks for the clarification.

**Comment by rljacob** [comment]
Just because E3SM are the only ones who use the feature, that doesn't make the test "E3SM specific".  Its a feature anyone could use and this is a test of it.
Please call  it something like "AWR.py" for "Archive While Running".  "STA" sounds like a generic test of short term archiving.

**Comment by jedwards4b** [comment]
What feature do you intend to test that IRT doesn't already cover?

**Comment by mfdeakin-sandia** [comment]
@jedwards4b I created a prototype test in scripts_regression_tests in my mfdeakin-sandia/test_sta_last_date branch - essentially it just tests the last-date option.
