### ISSUE TITLE
Compare two doesn't work on when casedirs and rundirs are on separate file systems

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#2031]
On titan, cases are put here:
~/acme_scratch/$PROJECT/$CASE

... and RUNDIRS are put here:
/lustre/atlas/proj-shared/$PROJECT/$USER/$CASE/run

SystemTestCompareTwo sets the OUTPUT_ROOT for case2 to ~/acme_scratch/$PROJECT/$CASE/case2, which means the RUNDIR for case2 is on the wrong file system.

**Comment by billsacks** [comment]
Okay, I think I see the problem. My mind is working slowly today, though, so it may take me a little while to come up with a robust solution (there may be an easy one, I'm just not grasping it immediately). @jgfouca or @jedwards4b feel free to chime in if you see one quickly :-)

The problem is that we were assuming that machines always put the bld and run directories under CIME_OUTPUT_ROOT. I think this is always true for all CESM machines, but that's not the case on titan:

```xml
    <CIME_OUTPUT_ROOT>$ENV{HOME}/acme_scratch/$PROJECT</CIME_OUTPUT_ROOT>
    <RUNDIR>$ENV{PROJWORK}/$PROJECT/$USER/$CASE/run</RUNDIR>
    <EXEROOT>$CIME_OUTPUT_ROOT/$CASE/bld</EXEROOT>
```

I think the setting of OUTPUT_ROOT for case2 is done correctly:

```python
        output_root2 = os.path.join(self._case1.get_value("CIME_OUTPUT_ROOT"),
                                    self._case1.get_value("CASE"), "case2")
```

but this is wrong:

```python
    def _get_case2_rundir(self):
        """
        Gets rundir for case2.
        """
        # Put the case2 run directory alongside its bld directory for
        # consistency. (See notes about EXEROOT in _get_case2_exeroot.)
        case2_rundir = os.path.join(self._get_output_root2(), "run")
        return case2_rundir
```

The problem is: Given that case1 and case2 have the same case name, and given that we want to keep their run directories separate (not critical, but highly desired): How do we specify the RUNDIR for case2 in a general, robust way? We figured out how to do this if we can assume that bld and run are nested under CIME_OUTPUT_ROOT, but I'm struggling with how to do this if we can't assume that.

**Comment by jedwards4b** [comment]
How about putting the case2 run dir under the case1 run directory:
case2_rundir = os.path.join(case1_rundir, "case2run")

**Comment by jgfouca** [comment]
I agree with @jedwards4b

**Comment by billsacks** [comment]
@jedwards4b good point.

I feel like we should then do something analogous for the bld directory:
case2_blddir = os.path.join(case1_blddir, "case2bld")

Do you agree?

And what should be done with CIME_OUTPUT_ROOT in this case? Is it fine keeping it as

```python
        output_root2 = os.path.join(self._case1.get_value("CIME_OUTPUT_ROOT"),
                                    self._case1.get_value("CASE"), "case2")
```

**Comment by billsacks** [comment]
Actually, I think I see a way that we could maintain the same directory locations for most machines that we currently have (i.e., `$CIME_OUTPUT_ROOT/TESTNAME/case2/bld` and `$CIME_OUTPUT_ROOT/TESTNAME/case2/run`) with something like this:

```python
case1_rundir_parent = os.path.dirname(os.path.normpath(case1_rundir))
case2_rundir = os.path.join(case1_rundir_parent, "case2", "run")
```

and similarly for bld.

I don't have strong feelings about this vs. @jedwards4b suggestion; do either of you? Although the above does seem slightly less robust if some machine has a very funny default rundir or blddir.

**Comment by jgfouca** [comment]
@billsacks that seems good. We don't want to reintroduce the path-too-long error that you fixed a while back.

**Comment by billsacks** [comment]
@jgfouca I think they're roughly equivalent in terms of the path-too-long error.

Assuming case1's bld and run dirs look like this:

bld: `/path/to/testname/bld/`
run: `/path/to/testname/run/`

(`/path/to/testname` could be different for bld/run, but in most cases they'll be the same)

The two options for case2 are:

(1) @jedwards4b 's suggestion:

bld: `/path/to/testname/bld/case2bld/`
run: `/path/to/testname/run/case2run/`

(2) Consistent with what we currently have:

bld: `/path/to/testname/case2/bld/`
run: `/path/to/testname/case2/run/`

I'm on the fence about it myself; do either of you care?

**Comment by billsacks** [comment]
Actually, I realized that (2) could fail in some pathological (but possible) cases; e.g., if a machine had rundir set to `/path/to/my/runs/$CASE`.

So unless I hear any objections, I'll do:

bld: `/path/to/testname/bld/case2bld/`
run: `/path/to/testname/run/case2run/`

and for CIME_OUTPUT_ROOT, keep:

```python
        output_root2 = os.path.join(self._case1.get_value("CIME_OUTPUT_ROOT"),
                                    self._case1.get_value("CASE"), "case2")
```
