### ISSUE TITLE
Our version of GPTL has memory leaks

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#2102]
I think this is a low priority issue, but our version of GPTL has some memory leaks. See https://github.com/ACME-Climate/tinman_sandbox/commit/7dbfb9a78f377009519b23cca60cf68c5d7b2890 for an example of a fix for one. Looking at the current version of GPTL, they seem to have numerous changes, and hopefully have fixed all of their leaks, so maybe upgrading would be a better solution than fixing it ourselves?
@worleyph

**Comment by worleyph** [comment]
Our version of GPTL and the current version have diverged, so it is not clear how best to resolve this. This is on my todo list however (and has been for awhile). I'd prefer to fix the memory leaks in our version until I can get to rebasing. The first memory leak only occurs right before GPTL fails, so is unlikely to be a problem (as a memory leak). Are you seeing memory leaks during actual runs?

**Comment by worleyph** [comment]
In fact this routine does not even exist in the current GPTL - Jim Rosinksi implemented this functionality without reference to our approach - not sure how different they are.

Looks like the suggested second free is a real memory leak. I'll keeping reading the code to verify.

**Comment by mfdeakin-sandia** [comment]
I only found this due to clang's address sanitizer, so there may be others in code I wasn't running

**Comment by mfdeakin-sandia** [comment]
Is there a test suite for GPTL which covers everything? That would make finding the rest of these easy

**Comment by worleyph** [comment]
@mfdeakin-sandia , thanks for finding this. The author of this code (merge_thread_data) also authored the routine collect_data, which has similar logic. In collect_data, newtimers is freed.

I'll do a quick test to verify that freeing this does not break this version of gptl and report back.

With regard to the other potential memory leak, neither this version of GPTL nor the latest from Jim Rosinski try to release memory when a malloc or realloc fails (which is the other example that you found). We could add this, but I am not knowledgeable about what happens when malloc or realloc fail. GPTL should probably abort when this happens in any case, but this is not the default behavior. Things will definitely go down hill after this, so the memory leak is unlikely to be irrelevant, as we are likely to have a seg. fault in the near future.

**Comment by worleyph** [comment]
@mfdeakin-sandia , I tested the addition of 

      free(newtimers);

at line 3377, immediately before 

      free(sort[0]);

and it worked fine (in at least one test program). Please submit a PR with this change (after fixing the indentation). I don't think that the other location you identified needs to be changed at the current time, but won't argue if others feel differently.

**Comment by mfdeakin-sandia** [comment]
Will do, thanks.

As a note, since malloc returns NULL on failure, attempting to free that is an error.
I agree that fixing the other leak isn't important for running, but it is helpful for using tools like address sanitizer, which I'm starting to do for all of ACME.

**Comment by worleyph** [comment]
Thanks for the explanation. I see a total of 7 instances  of this type of logic in gptl. (!(ptr=malloc()) && count) .
