### ISSUE TITLE
SCAM does not run with a real MPI library

### ISSUE THREAD

**Issue by kevans32** [ESMCI/cime#2304]
@jedwards4b I tried on both Edison and titan with out the mpi-serial turned off and got an "invalid communicator error" is there a test of SCAM (run nightly perhaps?) with MPI on that I can use to debug this? Else I have no working build of SCAM with MPI (or without in the multi-instance mode). Thanks as always for any info or direction you can point me.

**Comment by mvertens** [comment]
We have never tried to run SCAM in multi-instance mode. We do routinely
test CAM with SCAM now - but only in a single instance mode. @cacraigucar
can comment further on the SCAM tests that are currently being run.

**Comment by kevans32** [comment]
@jedwards4b says SCAM should work with MPI (not multi-instance- that is a separate issue #2295 although that is my eventual goal) so I am hoping someone has a script or test or something that I can use to exercise this capability, so thanks for tagging @cacraigucar. When folks test SCAM, do we test with MPI on or off? And do the ACME folks test SCAM on Titan or Edison or both, @jgfouca?

**Comment by rljacob** [comment]
@kevans32 Is it possible E3SM and CESM have different versions of SCAM?  You may need to open this on ACME-Climate.  Our one SCAM test uses mpi-serial.  Tagging @bogensch

**Comment by kevans32** [comment]
Oh sorry NCAR folks, I though this covered both and CIME was synced. Will do so.

**Comment by kevans32** [comment]
It would still be nice to grab a copy of a working script of SCAM with MPI from this version of CIME if there is one...I can try to port it over to titan...

**Comment by rljacob** [comment]
Point of clarification:   CIME gives people commands (create_newcase, case.submit, case.build) that they can use to write scripts to run specific compsets like SCAM but those scripts aren't part of CIME.  There are no SCAM scripts here.    The versions of CIME are synced and this would be the place to go if this was a CIME issue.

**Comment by cacraigucar** [comment]
Sorry to be so late in responding (working my way through a massive amount of email backlog)

CAM does routinely test our FSCAM compset.  It uses mpi-serial with no threads during the build process.

**Comment by jedwards4b** [comment]
@cacraig - it should also be able to run with mpi using a single task.  This is a useful feature for running ensembles of scam.  I can think of no reason this shouldn't work, but it currently doesn't and I believe it needs to be addressed.

**Comment by kevans32** [comment]
Is there a way to determine what the priority/timeline for addressing this issue is? I have a strong need for it, but I know there are many things to do. I have a project that requires the multi instance feature using SCM, so if I have an idea of when it will be addressed I can plan accordingly. Many thanks!

**Comment by kevans32** [comment]
@rljacob should put this in ACME as well?

**Comment by cacraigucar** [comment]
I am currently working on a tag of CAM which will allow SCAM to run using a single task in MPI (along with other SCAM changes/updates).  It should be committed later this week.  These changes are purely in CAM and have no spillover into CIME at all.

**Comment by jedwards4b** [comment]
@cacraigucar I think that when you complete this work we should add a multi-member scam ensemble test to our test list.

**Comment by kevans32** [comment]
I can give you a script of it once I get it going. @apcraig that is very soon- thanks! Should we move this to CAM?

**Comment by rljacob** [comment]
@kevans32, keep in mind that @cacraigucar is talking about fixing this in CESM's CAM.  I'm not sure how these fixes make it over to  E3SM.

**Comment by singhbalwinder** [comment]
@bogensch: Do you know how best to port these fixes to E3SM (if E3SM needs them)?

**Comment by bogensch** [comment]
If @cacraigucar is fine with sharing her work (with appropriate credit), then I can work on porting these changes to E3SM once the commit is made.

**Comment by gold2718** [comment]
Once it is on the trunk then the standard CESM developer agreement (http://www.cgd.ucar.edu/cseg/development-code.html) applies. If it is incorporated into E3SM, then it applies to anyone using the new capability with the E3SM code.

**Comment by cacraigucar** [comment]
Here are the promised diffs for the CAM code and are what went into our cam5_4_175 tag.  

diff cam5_4_170-TRUNK/components/cam/bld/configure cam5_4_175-TRUNK/components/cam/bld/configure
>1224,1233d1223
< # Check that model is configured for serial execution.  Note that configuring with spmd
< # and running with 1 task doesn't work because the EUL dycore expects at least 2 tasks.
< # The model should run if built for threading.
< if ($scam eq 'ON' and $spmd ne 'OFF') {
<     die <<"EOF";
< **  ERROR: SCAM mode assumes a serial build.
< **         Requested parallel modes are: spmd=$spmd  smp=$smp
< EOF
< }
< 

diff cam5_4_170-TRUNK/components/cam/cime_config/buildcpp cam5_4_175-TRUNK/components/cam/cime_config/buildcpp
>75c75
<     if mpilib == 'mpi-serial' or pts_mode:
 \---
\>     if mpilib == 'mpi-serial':
80c80
<     if int(nthrds_atm) == 1 or pts_mode:
\---
\>     if int(nthrds_atm) == 1:

diff cam5_4_170-TRUNK/components/cam/src/dynamics/eul/spmd_dyn.F90 cam5_4_175-TRUNK/components/cam/src/dynamics/eul/spmd_dyn.F90
>18a19
\>    use scamMod,          only: single_column
365,366c366,369
<       if (m2 < 1) then
<          call endrun ('SPMDINIT_DYN: Problem size is not divisible by 2')
\---
\>       if (.not. single_column) then
\>          if (m2 < 1) then
\>             call endrun('SPMDINIT_DYN: Problem size is not divisible by 2')
\>          end if
368a372
\> 
385,388c389,394
<       if ((dyn_equi_by_col) .and. (mod(tot_cols,2) /= 0)) then
<          write(iulog,\*)'SPMDINIT_DYN: Total number of columns(', &
<                    tot_cols,') must be a multiple of 2'
<          call endrun
\---
\>       if (.not. single_column) then
\>          if ((dyn_equi_by_col) .and. (mod(tot_cols,2) /= 0)) then
\>             write(iulog,*)'SPMDINIT_DYN: Total number of columns(', &
\>                tot_cols,') must be a multiple of 2'
\>             call endrun('SPMDINIT_DYN: number of columns must be multiple of 2')
\>          end if
