### ISSUE TITLE
Pre-tag testing scripts for CAM+DART

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#2455]
@mvertens @billsacks @jedwards4b @gold2718 
The last major step towards resolving #1807 is developing 
pre-tag tests of the CAM+DART software.  This is currently
dependent on the resolution of #2454, but we may be able
to start design work on it, and write/adapt a significant fraction
of the needed code before that's resolved.  
What are your thoughts?

**Comment by jedwards4b** [comment]
Why don't you use this issue to write out what you think that this test should look like.   Is there an expectation that dart would actually be run during this test?  If so how is it available to our testing team?   How many members of cam should be used?

**Comment by kdraeder** [comment]
I've re-read #1807 and it's still a good description of the 
heirarchy of tests that could be run for various purposes.
I also wrote a powerpoint with more detail, which I could
include, if that would be useful.  Or we could meet to go
over it again.
Some of the tests do not involve DART at all.  Others only
interact with a DART no-op script.  The most intensive
require building and running CAM+DART using DART's
and CIME's scripts.

**Comment by kdraeder** [comment]
@billsacks 
I'm picking on you because I remember your CGD
Research Report about pre-tag testing of components.

Can you point me to an example test in the latest CIME and/or CAM
that I could start looking at, as a template for the CAM+DART 
pre-tag tests we'll need?  I've worked through 
https://github.com/ESMCI/cime/wiki/CESM-System-testing-workflow
but it seems to be out of date with the CIME I'm using,
so it's hard to figure out where to start.
Thanks,
Kevin

**Comment by billsacks** [comment]
@kdraeder here are a couple of pieces we just discussed:

- https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide

- In https://github.com/ESCOMP/cesm/tree/master/cime_config you'll see testmods_dirs and testlist_allactive.xml . That's where we'll probably want to define this test.

@jedwards4b @mvertens @gold2718 I'm suggesting to Kevin that he define these DART prealpha/prebeta tests in the cesm allactive testlist: This doesn't seem entirely appropriate, but I can't think of a better place for them, since they will require at least one active cesm component (so can't go in cime), and there isn't a dart component of cesm that can hold these tests. Let us know if you can think of a better place.

**Comment by kdraeder** [comment]
@jedwards4b @mvertens @gold2718 @billsacks 
It may be a bit more complicated than finding 1 place to put testing.
The first test doesn't involve DART at all, so could be in a CAM test suite.
Other tests will minimally involve DART (DATA_ASSIMILATION_SCRIPT = 
...../noassim.csh), or may even involve running DART with CAM.

**Comment by kdraeder** [comment]
@billsacks 
I've figured out that I/we should set up a test in a testmods_dirs,
but I don't see one of those in a cesm or allactive directory, 
except in the cime_config directory.  But my impression is that 
this test doesn't belong in cime.  Is cime_config not really in cime?
Where should I put this test?

**Comment by jedwards4b** [comment]
This is the repo: https://github.com/CESM-Development/cime_config

**Comment by billsacks** [comment]
Huh, where did @kdraeder 's post go? Well, I'm replying to it here anyway:

> @billsacks
> I've figured out that I/we should set up a test in a testmods_dirs,
> but I don't see one of those in a cesm or allactive directory,
> except in the cime_config directory. But my impression is that
> this test doesn't belong in cime. Is cime_config not really in cime?
> Where should I put this test?

The repo @jedwards4b points to is the old cime_config. cime_config has now been folded in to the cesm repo. The cime_config in the cesm repo is probably the right place for this: that's not really in cime, it's just saying "this is cesm's configuration for cime".

**Comment by kdraeder** [comment]
@jedwards4b 
I realized a minute after I posted, that Bill had pointed me to the answer to
my question, so I tried to delete it.  That seemed to fail (or I needed
to update the page?), but then I had a follow on question, so I edited
the original post instead.  Now that doesn't appear either, so I'll start fresh.

Meanwhile @jedwards4b and @billsacks replied about which repo to use.
This is outside my experience with cesm.  I downloaded alpha08g from
> svn co https://svn-ccsm-models.cgd.ucar.edu/cesm2/alpha/tags/cesm2_0_alpha08g/
which is still the last one in there.
So can I set up this test in my local version of this?
Or do I need to check out the repo Bill (or Jim) pointed to?
And then my local cesm (except for CAM and ...?) will be under git control?

**Comment by jedwards4b** [comment]
CESM is here, instructions are on the web page
https://github.com/ESCOMP/cesm

**Comment by billsacks** [comment]
@kdraeder see replies below:

> I need to specify --multi-driver somewhere. I've been giving that to create_newcase, but I don't see how to do that in the testing environment. Is there a way to put it in shell_commands, or is that just for xmlchange commands?

It looks like you can do something like `SMS_C3` and you'll run with 3 instances in multi-driver mode. (I'm not sure if this is documented well, but I found it in test_scheduler.py.)

> For this test I need 80 instances of user_nl_{cam,clm,cice}_####, but the contents don't need to be unique. I can copy or link one into 80 unique names. In subsequent tests I'll need each instance to have unique contents. Both of these would be easier to do by using a script. Can/should the script live in cime_config/testmods_dirs/allactive/my_test_name along with the user_nl* and shell_commands?

As long as they don't need to be unique, you can do this with `SMS_C80`. Once you want to make them unique, since you want to do this by scripting, the cleanest way to do this would be via a new test type - i.e., a new python script. You do this by: (1) Adding a new entry in cime/config_tests.xml, and (2) Putting your new test script in scripts/lib/CIME/SystemTests. I'd start by following the example of sms.py (very simple). For an example of a test that appends things to user_nl files, see components/clm/cime_config/SystemTests/lii.py. This uses a function, append_to_user_nl_files, which is defined in cime/scripts/lib/CIME/SystemTests/test_utils/user_nl_utils.py. Right now that's written to append the same thing for all instances, but you could modify this so that it just appends something for a single instance and then have a loop over instances in your new test script - or maybe put the loop over instances in this utility area if it's generic enough.

> I've been using, and think it would be best to test, a compset that minimizes computation that a 6 hour CAM forecast doesn't need. I wasn't able to find a standard one that does what I want, so I've been using 2000_CAM60_CLM50%BGC_CICE%PRES_DOCN%DOM_SROF_SGLC_SWAV with --run-unsupported given to create_newcase. This has the same problem as --multi-driver. I also don't know whether it would work to put that in the a new testlist_dart.xml, since it doesn't have a short name.

You'll need to make an alias for this. For this compset, you should define it in CAM's config_compsets.

**Comment by kdraeder** [comment]
@billsacks @jedwards4b 
I believe that I've set up all the needed parts of the test,
but it's not using (some of?) my testmods.
I've defined them in
   /glade/p/work/raeder/Models/cesm2_0_alpha10e/cime_config/testmods_dirs/allactive/dartcambigens
I've defined a new test in testlist_allactive.xml (and testlist_dart.xml,
from when I thought it should be in a separate testlist).
I think that I'm correctly specifying testmods in the test.
I also defined a new compset alias in 
   components/cam/cime_config/config_compsets.xml
The command I execute to do a single test is
   create_test -v -r /glade/scratch/$USER/dartcambigens \
               SMS_C80_Lh1.f09_f09.FC6L5_HIST_FOREC.cheyenne_intel
Something builds and a job is submitted to the batch queue,
but it asks for 32 nodes/instance, instead of the 3 that I tried to specify.
It takes a long time to reserve 2560 nodes, and the job won't have the
other parts of my testmods, so I've killed those attempts.
I haven't figure out the connection between
    <entry id="NTASKS">
      <type>integer</type>
      <values>
        <value compclass="ATM">-32</value>
and NTASKS_ATM, which I'm specifiying in my testmods.
What am I missing?

**Comment by billsacks** [comment]
@kdraeder great, it looks like you're getting close.

When you run create_test, just change the test name to match the test name you have defined in the xml file, including testmods - i.e., `create_test ... SMS_C80_Lh1.f09_f09.FC6L5_HIST_FOREC.cheyenne_intel.allactive-dartcambigens`. This may not be clear: defining a test in the xml file is needed in order for that test to be run as part of an out-of-the-box test suite. But when you run a single test like this, no lookup is done in the xml file, so you need to tell it everything, including testmods.

Also, some other notes on your testmod that I noticed from a quick look through (I realize that this is more a commentary on our lack of clear documentation than anything else):

- In shell_commands: You set RUN_TYPE=hybrid, but aren't setting the REFCASE information; will this work?

- In shell_commands: Setting CONTINUE_RUN, RESUBMIT and DOUT_S is unnecessary, because that's already done via an SMS test.

- In shell_commands: You shouldn't need to set NINST, since that's done via the `_C80` in your test name. It's better to avoid setting these in testmods, so you can use the same testmods for (e.g.) a 2-instance test and an 80-instance test.

- In shell_commands: You're specifying 108 tasks and 80 instances. I believe this will give 2 tasks to some instances and 1 task to some instances. Is this what you mean to do?

- We generally try to avoid explicitly specifying NTASKS in testmods. Instead, you can use the `_PMxN` notation in the test name, where M is the number of tasks and N is the number of threads. One limitation is that it sets all components to the same task count, whereas here you're using fewer tasks for cpl. I'm not sure if there's an easy way to exclude cpl in that `_PMxN` notation.

- user_nl files: You don't need to have all of these sym links: If you want the same user_nl file for each instance, you can just have a single 'user_nl_cam' (etc.) file, and the test system should copy this to the appropriate user_nl files for each instance.

- user_nl_clm: The need to have a separate finidat_interp_dest file for each instance has finally been fixed, as of clm5.0.dev004 (which is in this alpha tag).

- user_nl_clm: Does it actually work to set finidat = 'finidat_interp_dest_nnnn.nc'? This looks wrong to me, but maybe there's some interesting usage that I've never come across.

**Comment by kdraeder** [comment]
@jedwards4b   Thanks for all the suggestions and clarifications!
I've made changes and the job is waiting in the queue
with the right number of nodes and tasks.

`RUN_TYPE=hybrid`; Good point.  I don't need hybrid for this test.
  I'll need to figure out REFCASE for later tests.

`Setting CONTINUE_RUN, RESUBMIT and DOUT_S is unnecessary;`
   Thanks, I thought that might be the case.

`You shouldn't need to set NINST, since that's done via the _C80 in your test name.`
   I was focused on trying to make it use fewer nodes
   and just imported commands used elsewhere.  I removed all those NINST lines

```
In shell_commands: You're specifying 108 tasks and 80 instances.
  I believe this will give 2 tasks to some instances and 1 task to some instances.
  Is this what you mean to do?
```
Multi-driver works differently; we need to specify the number of tasks for 1 instance. That number is multiplied by the number of instances to give the total tasks requested for the job.  I keep the single/multi driver question straight by asking myself "how many tasks does each driver need to run its instance or instances?"  

```
...specifying NTASKS in testmods. ... use the _PMxN notation in the test name, where M is the number of tasks and N is the number of threads. One limitation is that it sets all components to the same task count, whereas here you're using fewer tasks for cpl.
```
I don't remember a compelling reason for cpl to be limited to 1 node, except to avoid unnecessary(?) internode communication.  So I'll use the _P mechanism.  Thanks for the suggestion.

```
you can just have a single 'user_nl_cam' (etc.) file, and the test system should copy this to the appropriate user_nl files for each instance.
```
Good to know!

`user_nl_clm: The need to have a separate finidat_interp_dest file for each instance has finally been fixed`
Nice!

`user_nl_clm: Does it actually work to set finidat = 'finidat_interp_dest_nnnn.nc'?`
It has worked in previous versions, but it sounds like it's no longer needed.
Or will CLM not find and use the file created by interpinic?

**Comment by jedwards4b** [comment]
@kdraeder thanks for the acknowledgement but it's @billsacks who deserves the credit.

**Comment by billsacks** [comment]
@kdraeder thanks for all of these replies. Thanks for the reminder about the difference between multi-driver and single driver in terms of ntasks, and sorry for my mis-statement there.

Regarding this:

>> user_nl_clm: Does it actually work to set finidat = 'finidat_interp_dest_nnnn.nc'?

> It has worked in previous versions, but it sounds like it's no longer needed.
> Or will CLM not find and use the file created by interpinic?

The typical usage is to let finidat be set at its out-of-the-box default (i.e., _not_ set it explicitly in user_nl_clm), and (now that the multi-instance init_interp bug is fixed) not set finidat_interp_dest either. But it's possible that your use case requires something different. Feel free to give me a ring if you'd like to discuss this further.

**Comment by kdraeder** [comment]
Sorry @billsacks !  I should slow down and read the headers.
All your advice worked, and the test ran after I changed the wall clock to 20 minutes
and the queue to premium.

The TestStatus file shows all PASS through "MEMLEAK insuffiencient data for memleak test"  (which has an extra 'en' in insufficient).  
It generated the finidat_interp_dest_####.nc files,
but it's not as clear that they were used to start the model.

While waiting for the test to run I added to the create_test documentation, especially
testing.rst. Should that be part of what I push for a PR, or should that be a separate PR?

**Comment by kdraeder** [comment]
The test apparently worked
(SMS_C80_Lh1.f09_f09.FC6L5_HIST_FOREC.cheyenne_intel.allactive-dartcambigens).
Before the CIME code freeze this test was moved from allactive to cam
and the compset was renamed FHIST_DARTC6.
There will be extensions to this test, which use DART scripts and/or other components.
Those tests will also most likely be set up in the components, not CIME.
