### ISSUE TITLE
Subtle problem with xmlchange/xmlquery and case objects

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#247]
The issue is that when a case object is instantiated it reads it's xml data from the files on disk into memory, it then works with the data in memory until a flush is called which will update the files on disk.    However, the interface to external model components is designed so that they can be independent of the cime structures and rely on xmlquery and xmlchange to interact with the case.   So prior to calling any external model functions such as buildnml or buildexe you must call case.flush() to make sure that the case xml on disk is in sync with the case object in memory.  We are currently relying on developers to be aware of this situation and to issue case.flush() calls in all the right places.     

The erp test changes task and thread counts for a case and compares and runs a restart test.   This is expected to be bit-for-bit in cases that do not involve the pop ocean model.   However in cases that involve the cice model changes in the number of tasks require the cice component to be rebuilt and some decomposition data in env_build.xml (CICE_MXBLCKS, CICE_BLCKX, CICE_BLCKY, CICE_DECOMPTYPE) to be updated.   Since xmlchange is used by the cice buildnml to make these changes they update the xml files on disk but do not affect the case object in memory - in order to get the test to work I had to delete and re-initialize the case object in the test.     The erp test is now working on my branch but before I put this change on the trunk I thought that I would solicit suggestions from the community on a better way to assure that xml files on disk and the case in memory stay in sync.      Keep in mind that one reason the python version is so much faster than the perl is because we read and write the files on disk much less frequently, I don't think that we want to introduce an change that causes overly generous reading and writing of xml files - but maybe there is a way to do it just enough?

**Comment by gold2718** [comment]
One idea is to check the file modification time. Before flush is called and at key places in the code, a check could be done to look for any change.

1. If the in-memory object has been modified and the file has also been modified, this is an error condition (unless you want to try to re-read and merge changes).
2. If the file has changed and the in-memory object has not been modified, re-read to update.
3. If neither the in-memory object nor the file has been modified, flush can be a no-op.
4. If the in-memory object has been modified but the file has not, flush proceeds as it does now.

A function (cache_update?) could be written to check the consistency and return a file-modified flag. cache_update would update the in-memory object for case 2. flush would call this to see if it really needs to write (case 4), do nothing (case 3), or handle an error condition (case 1).

One caution with file modification times (instead of a slower checksum) is that if the file has been 'modified' by moving a non-modified file into the tested location, the file modification time check can fail. If this is a concern, it may be worth the checksum cost for a more robust solution.

**Comment by quantheory** [comment]
I don't have a solution for you, but I have a related problem to look out for. I notice that `case` has a `__del__` method (a destructor) that calls `flush`. This is probably bad, for two reasons:

1. `__del__` is nondeterministic, and pretty useless overall. Python doesn't guarantee that the `__del__` method will ever actually be called by the garbage collector, and in fact it definitely won't be for objects that are caught in any kind of circular reference (and the `Case` class is so complicated that it might be). So we can't use it to guarantee that `flush` is called.

2. Whenever a `Case` object is deleted or goes out of scope, then a flush will *potentially* occur, but we have no control over when that happens. If there are two `Case`s in existence for the same case in the same script, unless you carefully control the order in which they are created and when they are flushed, you could get some very weird bugs.

   For instance, let's say that you have a script where, for some reason, you want to throw away a modified `Case` without flushing it, and instead instantiate a brand new one corresponding to the data that's currently in the XML files. The old `Case` may or may not be automatically flushed, that may or may not happen before your new `Case` reads in the files, it may or may not happen while some child process is reading the files, and it may or may not happen *after* the new `Case` is itself flushed, overwriting the new data with whatever you wanted to throw away.

Honestly, I would just get rid of that destructor.

**Comment by gold2718** [comment]
Good point about unintended or ill-timed flush calls. However, instead of getting rid of the destructor, if we could use it to log unsaved changes (anything in self._env_files_that_need_rewrite) as a warning.

**Comment by quantheory** [comment]
I talked to Jim about this, and he pointed out that we probably do want to call `flush` when an exception is thrown, which is why that call is in the destructor. So I'm prototyping turning `Case` into a context manager (i.e. something you use with a `with` statement).

**Comment by jgfouca** [comment]
@quantheory that's an interesting idea. Just be mindful of performance.
