### ISSUE TITLE
add I/O volume information to timing files

### ISSUE THREAD

**Issue by bertinia** [ESMCI/cime#2645]
It would be helpful to include some estimated I/O volume information in the timing files. 
This info could then be parsed and displayed with the other timing data to help users
with estimates for size allocation requests. 

The algorithm used to estimate I/O volumes reported Gbytes/simulated year using a default monthly restart history file output size * 12 months / 1x10^9.
Note: CAM and CLM monthly restart history files sizes are first divided by 2 to account for double precision.

**Comment by mvertens** [comment]
This is a good idea. However, the I/O timing files don't have I/O turned on
by default (we recommend running the PFS test in the user's guide) . So
this would have to be obtained via another test that the user's ran.

**Comment by jedwards4b** [comment]
I would say that this is stronger than a recommendation - timings submitted to this page should be the result of running the PFS test.  IO can be turned on in the PFS test with a testmod.

**Comment by billsacks** [comment]
From the cime telecon: We could imagine this being something that the python scripts (maybe in the PFS test code) determine and output somewhere (though maybe not to the timing files, because I'm not sure if the python has easy access to that?): This seems easier than having the Fortran code determine this file size and output it to the timing files.
