### ISSUE TITLE
River 2 land interpolation and irrigation

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2909]
Here's an issue involving interpolation that maybe can't be solved by a better interpolation method.

(this is for E3SM)
When irrigation is turned on, the demand is calculated in ELM on the land grid (about 1 degree).   Its a field with sharp gradients.  The demand is interpolated to the river model (MOSART) grid (0.5 degree) with a conservative method.  The river model then determines how much is supplied for every grid cell that has a non-zero demand.  The supply is then interpolated back to the land model grid.  On that interpolation, some points that originally had no demand will have a supply, while points with a demand will get nothing.

All the mapping files (l2r, r2l) use ESMF conservative regridding.

To prevent water supply from going to points that had no demand, a fixer can be applied to redistribute water but that's not satisfactory.

The solution we're looking at is running the land and river model on the same grid which makes physical sense.  But is there a way to do this with interpolation?

**Comment by billsacks** [comment]
@swensosc and I solved the irrigation remapping problem in CESM by (1) having a custom remapping algorithm for irrigation, which withdraws water from each river cell proportionally to the river volume in that cell (see cime/src/drivers/mct/main/map_lnd2rof_irrig_mod.F90 and related code), and (2) having the capability for CTSM to limit its irrigation rate based on currently-available river volume. With these two things in place, I think we don't 100% prevent irrigation exceeding available river water (mainly or entirely because ROF isn't typically coupled every time step), but this is prevented in nearly all cases (and I believe that the remainder is handled by MOSART withdrawing water directly from the ocean rather than trying to route negative water).

It sounds like, in your case, you are doing some additional back-and-forth, where the land model computes a demand, the river model supplies as much as it can of that demand, and then the land model applies the provided supply – which, as you note, invokes the "diffusive" nature of remapping. I suppose you could do something similar to what we've done in CESM but the other way around, where you have a custom remapping of irrigation supply, where it is mapped proportionally to the demand in each land cell. But I wonder if something like what we've already done in CESM might work for you, too, and might end up being simpler.

**Comment by billsacks** [comment]
@rljacob on the cime call, I said that I can see how our method could lead for a given river cell's volume to be double-drawn-down, if it overlaps with two land cells. But I think I mis-spoke: Looking more carefully at how river volume (volr) is mapped from rof -> lnd, it looks like this is properly accounted for. For example, if a given river cell overlaps equally with two land cells, then (if I understand the code correctly) the volume in that river will be equally allocated to the two land cells for the purposes of irrigation limitation. So I'm back to not seeing a huge advantage to the extra back and forth done in the e3sm implementation, but I may be overlooking something.

**Comment by hydrotian** [comment]
@billsacks Thanks for the input! I'm working on the irrigation algorithm in E3SM. The reason we need to send the water back and forth is because we implemented water supply reservoirs in E3SM, which need to collect the demand information from the downstream grid cells and then decide how to distribute the irrigation water based on that. In another word, the supply in each land grid is not only from the streamflow in the overlapping grid cells, but also from multiple upstream reservoirs. I have attached some slides about this issue where you can find a diagram describing the model scheme.

[PI_meeting_2018_Zhou_coupling_issues.pdf](https://github.com/ESMCI/cime/files/2582692/PI_meeting_2018_Zhou_coupling_issues.pdf)

**Comment by billsacks** [comment]
Thanks @hydrotian . I can't say I fully understand it from these slides, but thanks for clarifying that there are some additional factors at play on your end.

**Comment by hydrotian** [comment]
@billsacks So if I understand correctly, your irrigation scheme is evaluating the water volume in the river from the land model side and use that to constrain the irrigation. No demand information will be sent from land to river model. Is that right?

**Comment by billsacks** [comment]
Right.
