### ISSUE TITLE
datm IAF dataset align year defaults

### ISSUE THREAD

**Issue by apcraig** [ESMCI/cime#3213]
The datm stream dataset align year is defined in this file,

 cime/src/components/data_comps/datm/cime_config/namelist_definition_datm.xml 

For single year data, the align year plays no role.  But for IAF (interannual forcing) datasets, the align year is important.  For some datasets, the align year is defined to be equal to the dataset start year.  For other datasets (in particular the CORE2_IAF and CORE_IAF_JRA), the align year is 1.  The problem with 1 is that if you set the model dates to be more realistic (say a start year of 1958 for a JRA case), the data atm forcing is not aligned properly.  The actual alignment depends on the start, end, and align years.  The JRA dataset is currently 1958-2016.  I think it would be better if the align year were also 1958 so when we're using actual dates, they align.  I think the CORE2_IAF (and maybe other IAF datasets) should be updated as well.

I know this will have an impact on users, especially if they are used to a different alignment, so know it's not an easy decision at this point (would have been better to do it at implementation).  But I think in the long term, it would be better to align the IAF data with the actual years of the data.  The other issue is that if the start and/or end years change, the alignment changes and demonstrates that an align year of 1 is largely ad hoc.

In the mean time, we're manually changing the align year in the input file via a user file in each case to facilitate this.

**Comment by billsacks** [comment]
This makes sense. See also #3093 , where we recently made a change like this for all land-related datm modes. @alperaltuntas what do you think about this?

**Comment by klindsay28** [comment]
I think that you are implying that users will set up their experiments so that model dates correspond to the date in the forcing. Am I understanding you correctly?

We typically run multiple cycles of the CORE2_IAF or CORE_IAF_JRA, and in this use case, the 1-to-1 correspondence of dates is broken.

I think this change would just introduce a new flavor of difficulty in interpreting model calendars, instead of altogether removing the current difficulty of this interpretation.

I'm inclined to not be in favor of this change, but am open to being persuaded.

**Comment by apcraig** [comment]
@klindsay28, then I'll try to persuade you.

As you point out, If you run multiple cycles, the 1-to-1 correspondence of dates is broken and it doesn't matter what the align year is.  In that case, the align year could be anything and you could start anywhere in the forcing dataset and just cycle multiple times.  Starting at the first year of forcing might be reasonable on some level but it's probably not scientifically different than starting in the middle of the forcing and cycling multiple times.

But if you run one cycle with realistic model years for the forcing data and the align year is incorrectly offset, you will be very confused and it will produce what I would consider incorrect results.  And that can be difficult to detect.  You will only notice if you look at the datm log file and see what forcing datasets are being read as the model advances in time.  I would say this is actually quite a big risk to the community.  Also, I know of users that run multiple cycles by running realistic model years and doing hybrid/branch runs to cycle, resetting the model year each time.  It is quite nice when the model year matches the year you're simulating and the interannual forcing has to line up for that to work correctly.  I believe this feature is something that some users want and even require in my experience.  

I think some of the interannual forcing datasets already set the align year as I propose, but not all.  It would be nice if there were some consistency, and I think what I'm proposing actually makes the forcing year alignment clearer.  It means when running realistic model years, the forcing is guaranteed to be aligned correctly.  At the same time, when cycling with arbitrary model years, there is little net difference in the simulations and I would argue, little to nothing lost by making this change.

**Comment by billsacks** [comment]
@klindsay28 - For what it's worth, Dave Lawrence and Sean Swenson recently asked for a change like this for land-forcing datm modes, following pretty much exactly the same reasoning laid out by @apcraig . A connected change was that we changed CTSM's config_compsets file so that present-day compsets (e.g., I2000...) started in a real year (e.g., year 2000) rather than year 1.
