### ISSUE TITLE
RCE Support in CIME for E3SM and CESM

### ISSUE THREAD

**Issue by whannah1** [ESMCI/cime#3249]
Turns out there was redundant work going on to build in RCE support by myself,  @cacraigucar, @brianpm, @kevinareed, and @jedwards4b . Comparing my version to the one that is already merged in with CIME from NCAR, there's at least one change I'd like to propose, and there might be other after I get a chance to dig into it more. There also might be more unmerged work at NCAR, so we definitely need to coordinate to avoid this problem again in the future.

The main thing I'd like to propose is having the constant SST mode be specified with a more descriptive name rather than AQP mode "11". I think "AQPCONST" makes more sense. In my version I added an XML variable to env_run.xml that also controlled a new docn_in namelist variable so that the SST value could be controlled by the compset (something like F-CAM-RCE300 vs F-CAM-RCE295).

**Comment by kevinareed** [comment]
Well, it is nice that we have multiple groups working on this as it ensures that the implementation will be correct in the end!  I think it would be nice if @brianpm shared his opinion on how to set the AQP configuration to a constant SST that is consistent with other activities in the simpler model efforts he is involved in. 

@whannah1 Are there any other issues you noticed in the implementation?  I know @cacraigucar was working on implementing the correct umin for the RCEMIP requirement.

**Comment by whannah1** [comment]
the Umin value only applies to the SCM case, right?

Two other issues I see are how the constant zenith angle and surface albedo modes are controlled. In my implementation I had created 2 namelist variables "constant_zenith_deg" and "constant_albedo" which were normally disabled with -1. 

The implementation of the "uniform_angle" and "seq_flux_mct_albdif/dir" is not clear to me. I don't get what makes the fixed albedo values are ignored in a non-RCE configuration. 

I guess the "uniform_angle" appraoch makes sense. I could keep my new namelist variable and just make E3SM pass that value to shr_orb_cosz(), although I'm confused why we are not using that currently.

**Comment by kevinareed** [comment]
The RCMIP Protocol states:
"If allowed by a model’s surface layer formulation, a minimum wind speed of 1 m/s should be enforced..."
So, I think it is true for all cases.

**Comment by whannah1** [comment]
Interesting... I need to look back at that. It seems like that would really constrain the surface fluxes and severely affect any aggregation behavior on the global domain.

**Comment by kevinareed** [comment]
Yeah, the point is to remove that as a variable for differences amongst models in the initial MIP.

**Comment by whannah1** [comment]
ah, well I can understand that then.

**Comment by brianpm** [comment]
Hey all. 

1. I like the more descriptive name AQPCONST. I guess my only concern with that is whether it complicates the logic associated with checking `set_option` ... maybe @whannah1 's solution doesn't bother with that. 

2. For Umin, @kevinareed and @cacraigucar and I have just been working on putting in another CIME namelist parameter to control it. I think that's the "right" solution, since this is an arbitrary value that shouldn't be hard-coded into CIME. 

3. For solar zenith angle, I don't love my changes to shr_orb_cosz(), but I do think that is where we should control the angle, so that all components would be using the same. (You know somebody's going to set up a fully coupled RCE one of these days.)

4. For albedo, I'm not sure how @cacraigucar finalized the implementation. If I remember, we were just going to have all composts besides our new QPRCEMIP one default to the old value. 

For all of these, I'm not super committed to our implementation (except we should focus on shr_orb_cosz() rather than orbit.F90).

**Comment by cacraigucar** [comment]
In answer to @brianpm question 4:
The "surface albedo for direct radiation" is being set in cime/src/drivers/mct/cime_config/namelist_definiton_drv.xml.    In there,  seq_flux_mct_albdif defaults to  0.06 for all runs and if aqua_planet_sst_type="sst_aquap11" then it sets it to 0.07.
