### ISSUE TITLE
maint-5.6 backward compatibility is broken

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3294]
PR #3266 introduced a change that is only valid with cam version 
https://github.com/ESCOMP/CAM/tree/cam_cesm2_1_rel_36 and breaks backward compatibility of cime maint-5.6 with older cesm and cam tags.   We need to introduce a fix to make cime backward compatible with older cesm and cam tags so that the maint-5.6 compatibility is maintained.

**Comment by jedwards4b** [comment]
I think that the problem was actually introduced in PR#3251 - is that correct?

**Comment by cacraigucar** [comment]
The bug was introduced in PR #3231.  In that PR, albdir and albdif were moved to namelist variables and defaults were set to maintain backwards compatibility.   Unfortunately, a missing MPI command was not discovered during development, review and testing which allowed values of zero to be set for these namelists.

I believe this bug was fixed in PR #3261 for the maintenance branch

It should be noted that this same bug was introduced into master, so the fix in PR #3261 needed to be applied to that branch as well.

It appears that Jim Edwards caught the bug on master prior to PR#3261 being reported, and he fixed it in
af01353a1f636f0778357855d6b6ee458b76db82

I believe this issue can be closed.

**Comment by jedwards4b** [comment]
The problem turned out to be a SourceMod in cime_comp_mod.F90 that the user copied from an old version of cime to a newer version.  The newer version had a call to seq_flux_readnl_mct, a routine that didn't exist in the older version.   So this namelist was never read and the variables were never initialized.
