### ISSUE TITLE
For data model configurations, should we document the modeling system responsible for each data mode?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#3308]
Inspired by #3307 - It's currently challenging to understand what data model modes are applicable to a given modeling system (CESM, E3SM, etc.). Should we have some way of documenting this? A simple thing to do would be to add comments in the xml files for each data model mode, saying which modeling system(s) uses and maintains the given data model mode.

A bigger change - but maybe a good one long-term - would be to have separate xml files describing the available datm modes for each modeling system, since I'd guess that these are more likely to be different than the same across modeling systems.

This seems especially important as cime grows to involve more modeling systems: As a CESM maintainer, I want to know which datm modes I should pay attention to, and which are just used by other modeling systems.

**Comment by klindsay28** [comment]
Is this content currently available in the compsets and/or tests that the components of a modeling system define. If so, duplicating the content in multiple places leads to the potential of the content getting out of sync, particularly since the duplicated content would span multiple repos (components and CIME).

Perhaps a tool that aggregates the content into a succinct form from the components of a modeling system would suite your needs.

**Comment by billsacks** [comment]
@klindsay28 yeah, I guess you're right. It is feeling wrong to me that we have a single xml file that defines all of the data model configurations across all modeling systems, when this feels like a pretty system-specific thing... but I guess I'll go ahead and close this for now, letting someone else reopen it if others feel this is an issue that should be addressed.

**Comment by rljacob** [comment]
The modes should be unique in some other aspect, exact data source, grid, frequency, that can be used to distinguish them.
