### ISSUE TITLE
Add a ne0 generic variable mesh resolution

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3328]
For the variable mesh community we'd like to add a generic resolution for these cases, that we are proposing to call "ne0". This will work similar to the "CLM_USRDAT" generic resolution that is used for CLM standalone "I" compsets. For those cases it was only allowed to be used with DATM and CLM. These cases should only be allowed when CAM is active. If in the most common cases prognostic ocean won't be used, it should probably also turn ROF off, and only allow OCN to be DOCN (as well as using SGLC).

It should also set EPS_AAREA=1.e-4d00 for these cases.

**Comment by ekluzek** [comment]
This might not need to be done if #3330 is completed. Check with Adam Herrington on this one. If the config grid file already sets the namelist resolution to be used in the user-mods-directory you won't need a generic one.

**Comment by adamrher** [comment]
I agree with @ekluzek here, that if [#3330](https://github.com/ESMCI/cime/issues/3330) is completed, the generic ne0 -res will not be needed, since config_grids.xml will have been appended with a the new grid_alias via the user-mods-directory.

But EPS_AAREA will need to be lowered for all variable resolution grids (conservatively, to 1.e-4), since this is currently the ONLY parameter that needs to be manually adjusted when running the three vr grids that AMP plans to roll out this year (see [CAM issue #61](https://github.com/ESCOMP/CAM/pull/61).

**Comment by adamrher** [comment]
@ekluzek do you want to go ahead and close this issue, and then I (or you) can open another issue addressing the EPS_AAREA issue explicitly?

**Comment by ekluzek** [comment]
@adamrher I can do that. How do you propose addressing EPS_AAREA for variable grids without having something like ne0 grid resolution name? Without that you have to explicitly change it for any variable grid right?

**Comment by adamrher** [comment]
This would be for the three specific supported variable resolution grid configurations (CONUS, ARCTIC, ARCTICGRIS) that I am trying to get into config_grids.xml in CIME. But I'm getting a little pushback on that plan right now, so let's hold off on opening a new issue until I get more clarity from the software engineers.

https://github.com/ESMCI/cime/issues/3330 is intended for eventually having the capability for cesm users to make their own grids, in which case yes, then EPS_AAREA can just be set in user-mods-dir.

**Comment by adamrher** [comment]
@ekluzek I think I misunderstood your comment. I think that perhaps a flag for EPS_AAREA could be conditioned by parsing the grid alias for a "ne0" since the procedure is to include ne0 in naming of the grids. For example, the ARCTIC grid alias is ne0np4.ARCTIC.ne30x4_mt12, and so this should trigger the flag. But I'm no software engineer...Either way, having a generic ne0 grid alias doesn't seem like the way to go.

**Comment by adamrher** [comment]
This issue should have been be closed, for reasons described in this thread. The EPS_AAREA issue has already been addressed and is moot now that we're no longe running MCT.
