### ISSUE TITLE
coupler namelist variable 'aoflux_grid' does not currently work

### ISSUE THREAD

**Issue by adamrher** [ESMCI/cime#3331]
The namelist variable 'aoflux_grid' is supposed to tell the coupler where to compute surface fluxes and wind stress - the atm grid or the ocn grid. I ran simulations toggling this namelist variable between atm and ocn, but the surface fluxes / wind stress were bit for bit between the two simulations, and so it doesn't appear this namelist variable is working. My understanding is these fluxes are computed on the ocn grid by default.

As shown in [Colin Z's GMD paper](https://www.geosci-model-dev.net/9/779/2016/), computing the surface fluxes / wind stresses on the atm grid is preferred for many variable resolution configurations ... And confronting this issue came out of a recent meeting to improve support for variable resolution configurations in cesm.

**Comment by rljacob** [comment]
What was your test case?  (compset and resolution).  For most F-cases, the atmosphere and data-ocean grids are the same so there would be no diff.

**Comment by adamrher** [comment]
It was a F2000climo compset with grid 'ne30pg2_ne30pg2_mg17'. So the 'mg17' part referring to gx1v7 ocean grid, isn't the grid used by the data ocean?

**Comment by jedwards4b** [comment]
@adamrher no - the mask does not determine the ocean grid, in this case it's ne30.

**Comment by adamrher** [comment]
Thank you both for clarifying this for me. Before I close this issue, did the ocean mask used to determine the data ocean grid, maybe within the last couple years? B/c Colin Zarzycki's 2016 study used an F compset and found a large sensitivity to aoflux_grid.

**Comment by jedwards4b** [comment]
Not that I know of - can we ask Colin for some clarification?

**Comment by zarzycki** [comment]
Total drive-by comment...

It is my understanding that it used to be (~5 years ago?) that ne120_ne120 didn't exist, it was ne120_gx1v6 (set up for both B and F compsets).

According to Tony Craig, the default behavior was to compute fluxes on the ocean grid (historically, I believe ocean grid spacing was finer than atmosphere). However, when the atmosphere is of a higher resolution than the ocean, this results in inconsistent drag calculations since they are "smoothed" over the low resolution ocean cell. This resulted in errors in extreme surface wind speeds that we noticed in hurricane simulations.

So at some point Tony added the aoflux_grid which allowed us (Julio B. and I) to compute the surface fluxes on the atmosphere grid when we ran ne120 or variable-resolution. This became our de facto "default" option when the ocean and atmosphere grids weren't identical.

Note that this problem is totally alleviated by just running the ocean domain as matched to the atmosphere so every column is one for one (eliminating the mapping in the coupler). This is my STRONG recommendation for new F compsets using VR-CAM-SE.

That said, making sure the capability to calculate fluxes on the atmospheric grid stays seems prudent as running any B compsets you will have mismatched grids (since MOM + CAM-SE won't run the same grid). So the problems we saw in the GMD paper Adam linked will happen if, for example, you run 1deg ocean and a VR atmosphere down to 0.25deg.

Let me know what needs to be clarified there, I can dig up my old e-mails with Tony, too.

**Comment by adamrher** [comment]
OK thx. It think my confusion comes from that it used to be more standard to have a grid alias in the form of <atm/lnd>_<ocn>" for example ne120_ne120 or ne120_gx1v7 ... but at some point cesm added a third modifier  <atm/lnd>_<ocn>_<mask> which specifies the land ocean mask if <ocn> == <atm> ... and so obviously aoflux_grid won't make a difference in my ne30pg2_ne30pg2_mg17 runs.

If Im interpreting config_grids correctly, the tri-grid has a slightly different interpretation for the grid alias: <atm>_<lnd>_<ocn/mask>
