### ISSUE TITLE
shr_sys_irtc is not thread safe

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#3357]
Originally reported by @worleyph 

The variable irtc_rate was mistakenly left out of the private variable declarations in the OMP directives implementing threading over chunks in EAM (and CAM?) in three locations in physpkg.F90. This leads to errors, confirmed on both Cori-KNL and Compy. This error is only obvious when the user_nl_cam option

 `phys_chnk_cost_write = .true.`

is set, but it is occurring in every threaded run (just not causing any other problems, that I am aware of).

Adding irtc_rate to the list of private variables was not sufficient. The utility routine shr_sys_irtc is itself not thread safe. **Surrounding the calls to this routine with critical sections in physpkg is sufficient to eliminate the chunk cost calculation failures when threading**. 

Based on experiments on Compy, shr_sys_irtc can be made thread safe if we wrap the whole body of the routine in a critical section, including the call to system_clock. However, even if system_clock is thread safe (why wouldn't it be?) there are local save variables that are updated within the routine, and so are subject to race conditions when called within a threaded region, so most of the body would need to be in a critical section in any case.

**Comment by worleyph** [comment]
@amametjanov proposed what appears to be the correct solution (for shr_sys_irtc), to declare the local save variables to be threadprivate. The variable irtc_rate as used in physpkg.F90 (in EAM) still needs to be added to the PRIVATE clause in the OMP declarations. The combination of the two worked to elimiante the errors on Cori-KNL and on the Compy system at PNNL.

**Comment by billsacks** [comment]
My (possibly incorrect) understanding of threadprivate is that there are a number of restrictions on its use, including that you always are using the same number of threads in all parallel regions. Yet my understanding is that cime supports (or at least aims to support) different components having a different number of threads. Are you sure that threadprivate will work correctly in this more general use case?

**Comment by billsacks** [comment]
(The alternative I can see off-hand if threadprivate is not a robust solution in cime's source code would be leaving it up to the caller to save `last_count` and `count_offset`, and requiring the caller to guarantee thread safety. This could be more robust because a given component typically will use the same number of threads throughout its lifetime.)

**Comment by worleyph** [comment]
or we can simply declare shr_sys_irtc to not be thread safe and always wrap it in a critical section when it is called. I hope that this is not the best solution however. I initially implemented the logic in physpkg.F90 using MPI_WTIME, but moved to shr_sys_irtc to avoid having to use mpi-serial (which was a problem for a reason I can't remember now).
We do currently support using a different number of threads in different components, at least in E3SM. I'll add shr_sys_irtc calls to other components and test this scenario and see what happens.

**Comment by worleyph** [comment]
@billsacks , any idea what a failure would look like? Ran with ATM and LND overlapped (ATM larger than LND), with 8 threads used by ATM and 3 threads used by LND, and calls to shr_sys_irtc with the threadprivate declaration seemed to have worked fine. Also tried 8 threads for both, to establish a baseline. This experiment had 1 chunk and 1 clump per thread. I'll look at having more, so that threads move through the chunk/clump loops more than once.

**Comment by billsacks** [comment]
I'm not sure... but thinking out loud here: It seems like the issue with using threadprivate with varying number of threads is the association between a given value of the threadprivate variable and the thread. If you initially create 8 copies of the variable and then later have 3 threads, the association between threads and values is undefined... and the problem is worse if it's possible to go the other way around. Now, in this particular function, that may be okay... I'm not sure....

According to https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference-threadprivate

> For subsequent parallel regions, data in THREADPRIVATE common blocks are guaranteed to persist only if the dynamic threads mechanism has been disabled and if the number of threads are the same for all the parallel regions.

This makes it sound like you could be open to subtle compiler-specific bugs.

This makes me inclined to use a critical section unless (1) that is a problem for performance, and/or (2) you or others can provide a good enough understanding of this to be confident that threadprivate is a safe way to go.

**Comment by worleyph** [comment]
I'd prefer that others make this decision (@amametjanov ? @rljacob ? ). As is, shr_sys_irtc is demonstrably not thread safe. Adding the threadprivate declaration makes it somewhat thread safe, and perhaps is sufficient for the current use case, as described below. Perhaps it could then be used in another fashion that would be inappropriate - is having it possibly subject to subtle errors worse than always being in error in threaded regions?

The current use case is as follows:

     !$OMP PARALLEL DO PRIVATE (c, beg_count, irtc_rate, end_count, chunk_cost)                
            do c=begchunk, endchunk
               beg_count = shr_sys_irtc()
     ...
               end_count = shr_sys_irtc(irtc_rate)
               chunk_cost = real( (end_count-beg_count), r8)/real(irtc_rate, r8)
            end do

so all that matters is that the counter values beg_count and end_count are consistent with each other during one iteration of the loop, not that they are consistent across multiple iterations nor between threads.  If a thread creates a "copy" of last_count and count_offset at the beginning of the loop, when setting beg_count, updating them as necessary, and then examines and updates them again, if needed, when setting end_count, that is all that is needed here. If no other thread can stomp on these, we should be okay?

**Comment by billsacks** [comment]
My main feeling at this point is that, if this is fixed in a way that is only kind-of, sort-of, maybe threadsafe in some circumstances, then there should be clear comments added to the header of this routine cautioning about its use in threaded regions. Other than that, I'm happy to defer to E3SM how it is solved, since the only use of this function I see in CESM is in the driver, which doesn't use threading.

**Comment by amametjanov** [comment]
I don't see a way to "break" these `threadprivate` variables in practice. Within components (ATM or LND), number of threads stays constant and there are no `call omp_set_dynamic(.true.)` in sources or `export OMP_DYNAMIC=TRUE` in scripts. Both begin and end calls to `shr_sys_irtc` are around small code sections (not even across `omp parallel` regions). Data doesn't need to persist between two pairs of calls.

It's possible to call `shr_sys_irtc` in ATM with 8 threads and then in LND with 3 threads to measure elapsed time between the two calls: not sure why that could be needed. To avoid such scenarios, a doc-comment could say
```
This function is not intended to measure elapsed time between multi-threaded
regions with different number of threads.
```

Forcing callers to add `omp critical` to every call to `shr_sys_irtc` seems to add unnecessary synchronization bottlenecks.

**Comment by billsacks** [comment]
I'm happy with the rationale and comment proposed by @amametjanov - I agree that, if this is just used to compare values from begin and end calls within a single threaded region, the proposed solution feels safe.

**Comment by worleyph** [comment]
I'll add the following comment to shr_sys_irtc in the E3SM-side PR:

     This function is not intended to measure elapsed time between
     multi-threaded regions with different number of threads. However,
     use of the threadprivate declaration does guarantee accurate
     measurement per thread within a single multi-threaded region as
     long as the number of threads is not changed dynamically during
     execution within the multi-threaded region.

then let @amametjanov make any further updates as he feels appropriate. This can then be revisited by everyone else once the changes are merged into CIME.
