### ISSUE TITLE
Addition of a `srcExclude` file for selective compiling

### ISSUE THREAD

**Issue by fritzt** [ESMCI/cime#3366]
As part of the coupling between CESM and GEOS-Chem, we propose adding a `srcExclude` file that would list any files that do not need to be compiled. For instance, when coupling the GEOS-Chem chemistry modules with CESM, the advection files from GEOS-Chem do not require to be compiled, as CESM performs the advection.

We intend to add two types of `srcExclude` files:
- Any directory in `Filepath` could have a **local `srcExclude`** file. This file would be folder-specific and contain only the **local name of files to exclude**. Any missing files from the list would be discarded.
- A **global `srcExclude`** with **full pathnames relative to the component's root folder**. This file could be used, for instance, to exclude unnecessary GEOS-Chem files. The GEOS-Chem folder would be unmodified from its Github repository, thus we do not want to add any local `srcExclude`.
 
These files could be read from `mkSrcfiles`. Any new `srcExclude` file would push the new content to an array of excluded files.

I want to open this up for discussion and I welcome any potential suggestions.

**Comment by jedwards4b** [comment]
Sounds great to me, @jgfouca any concerns with this?  Do you use mkSrcfiles with the cmake build?

**Comment by gold2718** [comment]
This would also be useful for the CESM DART component. Currently, we have to copy the files we want to compile into the bld directory.

**Comment by billsacks** [comment]
I agree this sounds good. It made me wonder about the pros and cons of having an exclude file vs. having an explicit list of files _included_ in the build. But I think the main arguments for requiring an explicit list of included files, at least in CMake-based builds (namely: an explicit file list allows CMake to know when it needs to be rerun, which is important for incremental rebuilds: see https://stackoverflow.com/questions/32411963/why-is-cmake-file-glob-evil) don't apply so much to us, because it's much more common for us to build from scratch rather than doing a lot of incremental rebuilds. So the exclude idea makes sense.

**Comment by gold2718** [comment]
@billsacks, I agree that an include file would be great for cases where you can add such a file to the target directory. For cases such as GEOS-Chem, we are trying to bring this external into CESM without modifying the source repo. So in this case, a global _exclude_ file is easy to use while a global _include_ file would not easily play nice with the rest of CESM.
I suppose you could just write a global component Srcfiles and skip running mkSrcfiles.

**Comment by jgfouca** [comment]
@jedwards4b , the cmake build system doesn't use mkSrcfiles (it uses Cmake code to do essentially the same thing it was doing). Feel free to make any changes you want to mkSrc.

**Comment by rljacob** [comment]
What I like about a list of files to include is that list could have the logic for build options where you have a bunch of files in common but need one or 2 files to be included or not. Right now we need separate directories for that logic.
