### ISSUE TITLE
Store compset ailas in the env XML files

### ISSUE THREAD

**Issue by douglasjacobsen** [ESMCI/cime#342]
It would be useful if the compset alias was accessible somewhere within the env XML files (i.e. env_run.xml, etc..) so components are set default namelist values based on the actual compset that is being used instead of only using the grid.

**Comment by quantheory** [comment]
Can you clarify what sort of scenario this would be useful for? Compset aliases are entirely a user-interface feature; I'm very skeptical about making them participate configuration/namelist logic. That's what the long name is usually for, and the long name *is* stored in `env_case.xml`.

**Comment by douglasjacobsen** [comment]
@quantheory Sure. This actually is what motivated the question in slack:

> Are compset aliases required and do they have to be unique?

So, typically the compset determines the coupling intervals. Additionally, there are components who's time steps need to be the same as the coupling intervals.

Within ACME for example, we have a G case that has 1 hour coupling intervals, but the corresponding B case (at the same resolution) has 30 minute coupling intervals.

So, the models that are part of that need to make time step adjustments, if they are longer then 30 minutes, strictly based on the coupling interval.

The options are to add some complicated logic to the buildnml scripts for those components, so that they grab the coupling intervals and build out a time stamp, or to have a default keyed off of the compset name. It's possible that the long name could work, but it would make the defaults file pretty difficult to read.

This might be useful in other ways though, so that you could have a compset enable different physics options more easily (kind of like how BGC/BEC is used), by setting namelist options in some components.

**Comment by quantheory** [comment]
Hmm, TBH I would probably try to figure things out from the coupling intervals in this situation. It feels like, if that's really so complicated, then there's something wrong or some missing functionality to be addressed there. It also makes me nervous to assume connections between things that don't have an obvious or intrinsic relationship (e.g. there's nothing inherent to G cases that forbids 30 minute coupling), because eventually the connection will break.

That said, I don't think that this would be hard to do using the long name in `config_component.xml`. That's currently how components figure out how to configure themselves, and also check things like BGC. But there's nothing in principle to stop active components from checking for *each other's* presence and settings. For instance, in CESM, CICE has a CAM4 compatibility flag, and we set it with a line that looks like this:

```xml
<value compset="_CAM4">cam4=.true.</value>
```

It's not elegant for active components to be "nosy" and examine each others' settings, but given that sometimes you have to do it, I don't think that it's hard to do via long name, since this is the sort of information that the long name was specifically implemented to provide.

**Comment by douglasjacobsen** [comment]
I'll try to play around with the long name and see if I can make it work how I'd like. So for now I'll close this issue, and then I'll re-open if I need to revisit it.
