### ISSUE TITLE
avoiding div0 in cprnc

### ISSUE THREAD

**Issue by rgknox** [ESMCI/cime#3525]
I had been running into an issue with cprnc while running regression tests with CTSM-FATES on cheyenne.

https://github.com/ESCOMP/CTSM/pull/1007#issuecomment-626871444

When comparing two arrays (base and test), if the base had only zeros in an array, but the test had non-zero values, it was enabling a comparison between the two. However, the normalization factor was using the zero value, and hence trying to calculate a div0.  

*Note, in this case, the arrays that were generating the div0 were integer arrays defining the dimensions.

I hacked up some modification, and was able to get the test to stop trying to divide by zero. It also identified that the fields were different in the final summary.

Here are my modifications:
https://github.com/ESMCI/cime/compare/master...rgknox:fix-div0-compare_vars

I'm not too familiar with the code, so I didn't want to issue a PR with any changes until some others looked at this and made suggestions.

**Comment by jedwards4b** [comment]
I think that this change is fine and should be submitted as a PR.

**Comment by klindsay28** [comment]
Consider changing `>1.e-20_r8` to `>0`. I glanced quickly through some test run output and found some CAM variables (`bc_c4`, `bc_c4SFWET`, `pom_c4`, `pom_c4SFWET`) whose `avg abs field values` can be < 1.e-30. (This is `avgval` in the code.)

**Comment by billsacks** [comment]
Yes, please open a PR. I have trouble imagining this occurring in practice for real-valued arrays, but a fix seems in order for integer-valued arrays. However:

1. I agree with @klindsay28 that the check should be for `> 0`

2. I feel like you should report a normalized rms of [huge](https://gcc.gnu.org/onlinedocs/gfortran/HUGE.html) in this case: the numerator is `> 0` but the denominator is 0; the result *should* be infinity, but that can't be represented, so the closest thing to correct that you can do is to report a huge value. Reporting 0 is misleading because it suggests that there is no difference when really there is one.

**Comment by rgknox** [comment]
agreed @billsacks , thanks all, will open a PR

**Comment by billsacks** [comment]
See https://github.com/ESMCI/cime/pull/3530#issuecomment-627036709 for notes on what I believe is the underlying issue.
