### ISSUE TITLE
QBOT for 2014 data in atm_forcing.datm7.GSWP3.0.5d.v1.c170516 is zero

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3653]
The 2014 data for QBOT in the GSWP3.v1 forcing is zero. Which of course means you can't get reasonable results when running over 2014. So any simulations that used 2014 forcing in them would be bad. This would be for historical or future scenario simulations as they both go to 2014. Future scenario simulations cycle over forcing so each time it cycles over 2014 it would be bad.

Since, we can't just overwrite existing data with new data the only way I see to fix this is to create a new directory where we place soft-links for the non-2014 data and the updated 2014 data. So there could be a new data directory called

atm_forcing.datm7.GSWP3.0.5d.v1.c20806

I'm not sure if we'd consider this a new "version" hence start referring to it as "v2" or not.

@billsacks

**Comment by ekluzek** [comment]
Future simulations cycle over 2001-2014 data. So every fourteenth year of the future simulation would be bad. And having zero humidity for an entire year would also be bad for anything after that year. I suppose it might recover in the next year, but it would start the simulation down a very wrong path. Precipitation would still be happening, but all evaporative fluxes would just be wrong.

**Comment by ekluzek** [comment]
Sean Swenson has the corrected data here: /glade/scratch/swensosc/GSWP3/three_stream/TPHWL/ on cheyenne. It looks like this issue was discovered in 2018 and Hyungjun Kim <hjkim@iis.u-tokyo.ac.jp> uploaded new data for us to http://hydro.iis.u-tokyo.ac.jp/~hjkim/qair-updated/GSWP3.Qair.2014-2014.nc. That data is still available and what Sean used to create the files on cheyenne (only QBOT is overwritten).

**Comment by ekluzek** [comment]
I should be able to add softlinks to the svn repository. But, need to look into how this will be handled by the other protocols: wget, ftp, and gftp. The other complication of softlinks is that in order to get all of the data you'll need to download the complete current GSWP3v1 dataset and then download the 2014 update afterwards. So it's a little more awkward to handle.

**Comment by ekluzek** [comment]
I'm checking with Mark Moore if the other protocols can handle softlinks. Also note that these softlinks will need to be for a relative and NOT an absolute path, so that they will still make sense on any system. As such we probably want to create a script that will create the softlinks, and we might as well upload the script to inputdata as well. Another way to handle it would be to download the script to a given machine and then run it, rather than downloading the softlinks using the usual mechanisms.

By the way if E3SM people use GSWP3v1 data for 2014 -- this will be a problem for them as well. @jgfouca @bishtgautam

**Comment by bishtgautam** [comment]
@ekluzek Thanks for bringing this to my attention.

**Comment by ekluzek** [comment]
In looking through the data @olyson found that QBOT=0 is for the last time slice of 2013-12. So we'll need to fix that as well.

**Comment by billsacks** [comment]
I don't totally understand the workflow you're suggesting for obtaining the new data, but I'm wondering if it would be possible to instead provide some mechanism in CIME's stream input file generation to allow for overrides – so that it would take this:

```
      <value  stream="CLMGSWP3v1.TPQW">clmforc.GSWP3.c2011.0.5x0.5.TPQWL.%ym.nc</value>
```

with some following entries for a handful of overrides, and use those overrides for the select years/months where they are specified. I'm not sure exactly what that would look like, but if it's not too hard, it feels like it would keep things more seamless for users.

**Comment by ekluzek** [comment]
Well I do like the idea that you proposing. That would be useful in some circumstances. It would have to be configured so that the override came into play for particular years though. So I think it would have to have something like...

``` xml
  <value  stream="CLMGSWP3v1.TPQW" ym="2014-01">clmforc.GSWP3.c2011.0.5x0.5.TPQWL.%ym.nc</value>
  <value  stream="CLMGSWP3v1.TPQW" ym="2014-02">clmforc.GSWP3.c2011.0.5x0.5.TPQWL.%ym.nc</value>
.
.
.
 <value  stream="CLMGSWP3v1.TPQW" ym="2014-12">clmforc.GSWP3.c2011.0.5x0.5.TPQWL.%ym.nc</value>
```

That kind of thing could be useful because looking at the files there are often overrides for a few particular years, but the rest follow a pattern that could use the %ym marker. And right now the only way we have to express those overrides is to list each filename individually for the entire series and NOT use the pattern markers. So it makes the namelist_definition file much, much longer than it needs to be.

This would be a useful development. I'm not sure how much time it would take to do. It would be longer than the softlinks -- but be a better implementation that would also help other things.

**Comment by ekluzek** [comment]
In talking with Dave Lawrence we think the stopgap measure we should put in place for the CESM2.2.0 release is to make the end year by default 2013 rather than 2014. And also possibly add a note to the xml file about 2014 being a problem. I could also add a README note in the data directory about it.

**Comment by ekluzek** [comment]
Let's move the discussion of the general long term issue to #3662. This will be here for the specific issue with GSWP3.

Now the plan is to resolve this in at least two steps. One will be to change the default end year to 2013, and another will be to have a GSWP3v1.1 stream update that will either be implemented with the solution in #3662 or with softlinks. Or possibly we'll do softlinks first and then the general solution later.

**Comment by ekluzek** [comment]
Reopening this, because the current fix is to just not use 2014 data. Longer term we want to use the corrected data.

**Comment by billsacks** [comment]
Thinking about possible ways to address this (other than #3662 , which @mvertens thinks won't be worth the time):

- I raised the possibility of listing out all files explicitly, but @ekluzek pointed out that, in addition to maintainability issues, there are performance issues related to reading in all files in initialization rather than just the subset of years you need for your case

- @ekluzek has proposed using sym links. This would be easy to implement and maintain, but would likely will be a challenge for users on new systems, where they don't already have the old dataset

- Another possibility I just thought of: instead of storing sym links on the server, could we use `svn copy` to copy these files on the subversion server? I think that would avoid using extra space on the subversion server. We could still create sym links on the local disk on our systems (cheyenne, izumi and others we maintain) to prevent the newly-named files from being copied down. I think this would make it seamless for people on new systems to get the data. The problem would be that, for people on systems where they already have the old data, they would end up with two copies with different names (and the corresponding extra usage of disk space) unless they did something up-front to prevent this (i.e., created sym links) and/or removed the old data afterwards. One other possible issue is: if the svn server is being mirrored by other inputdata servers at this point (I'm not sure if this is the case), then they wouldn't have a notion of `svn copy`, so I'm not sure how they would handle this... they might end up with duplicates of the data.

**Comment by billsacks** [comment]
@ekluzek if a fix is still needed for this, can you open an appropriate issue in cdeps and close this one?

**Comment by billsacks** [comment]
Given that there is no good solution, we should probably just make a copy of the data; @ekluzek can you open an issue to this effect in cdeps?

**Comment by billsacks** [comment]
From discussion with @dlawrenncar we might stop using the GSWP data, so let's hold off on doing anything major until that's decided. But this should probably still be moved to cdeps.
