### ISSUE TITLE
pio_log_N.txt files

### ISSUE THREAD

**Issue by amametjanov** [ESMCI/cime#3857]
Running E3SM cases in debug mode produces these one-per-process empty files: e.g.
```
cime/scripts/create_test SMS_D.f19_g16.X
```
Not sure how to disable.
```
cime$ git describe
cime5.8.37-37-gf90d23a
```

**Comment by rljacob** [comment]
What files?

**Comment by ndkeen** [comment]
I noticed this as well

**Comment by amametjanov** [comment]
`pio_log_N.txt` files

**Comment by rljacob** [comment]
When you build E3SM, these must come from SCORPIO.  @jayeshkrishna or @dqwu ?

**Comment by jedwards4b** [comment]
When you build in debug mode it enables PIO logging.  When logging is enabled the log files are created even when the log level is set to 0.   It's a feature.

**Comment by amametjanov** [comment]
Since files are empty, can we disable creating files if `PIO_DEBUG_LEVEL=0`?

**Comment by rljacob** [comment]
I'm sure we can but, again, this probably has to be done in SCORPIO.  I suggest opening this issue on the SCORPIO github.

**Comment by jedwards4b** [comment]
This is controlled in the buildlib.pio in cime - but if you disable logging by default the PIO_DEBUG_LEVEL becomes a build option instead of a runtime one and might be even more confusing than creating a bunch of empty files.

**Comment by rljacob** [comment]
Isn't opening the files done by PIO/SCORPIO?  Add logic to not open them if PIO_DEBUG_LEVEL is 0. The files should only be created if something is going to be output to them.

**Comment by billsacks** [comment]
Just to add another opinion here: I would also vote for having these files _not_ appear by default. On jobs with hundreds of tasks, I haven't loved the way these files fill up the run directory. I don't understand the details of what @jedwards4b is saying, but if the only implication is that you would need to rebuild after changing PIO_DEBUG_LEVEL, I personally feel that is a reasonable price to pay for not having these files appear by default. It seems like an added benefit is that we could turn on pio logging just based on PIO_DEBUG_LEVEL, so that it could be enabled in non-debug runs if desired. (Or is that not possible for other reasons?)

@jedwards4b you mention buildlib.pio, but I wonder if the relevant logic is actually this?:

https://github.com/ESMCI/cime/blob/2604dd66333107009777f57599f005a931861337/scripts/Tools/Makefile#L672-L674

**Comment by jedwards4b** [comment]
@billsacks yes, sorry - it's in the Makefile.   I've submitted a PR https://github.com/NCAR/ParallelIO/pull/1855 to pio to not create these by default. but changing PIO_DEBUG_LEVEL is not the only way to enable logging, you can also add a pio_set_log_level call in the code.

**Comment by billsacks** [comment]
Thanks @jedwards4b !
