### ISSUE TITLE
Some vars resolve too early

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#406]
Reported by @jedwards4b:
Some variables in env_*.xml files are being resolved too early - this results in a number of problems including one found by John Truesdale: If the variable CASE is defined in the environment when you ran create_newcase then the EXEROOT and RUNDIR would be defined using the CASE from the environment instead of the one in the create_newcase argument.

**Comment by mnlevy1981** [comment]
Closed #326 because it seems to be the same issue as this ticket -- `$CIMEROOT` is also picked up by `create_newcase` if it is in your environment. From talking with @jedwards4b it seems like some CIME scripts (`configure`, for example) do need `CIMEROOT` in your environment (and `create_newcase` needs other environment variables such as `$USER`), but perhaps there is a way to limit which scripts look for which variables in the environment?
