### ISSUE TITLE
black should reformat and not just error out

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4211]
The action in cime/.pre-commit-config.yaml
just gives an error if black isn't happy with format, 
I would prefer that black just go ahead and reformat the file.

**Comment by mvertens** [comment]
@jedwards4b - how do we know that this would not possibly introduce an error?

**Comment by jedwards4b** [comment]
If it introduced an error that error would be flagged in the github actions.   As is you submit a PR
black runs and fails and you run black locally and resubmit the PR.   I don't do any further local testing
for this and I doubt others do either.   I'm tired of having to explain that you need to install black locally and
run it on the file in question then re-push the PR.

**Comment by jasonb5** [comment]
The benefits to introducing pre-commit are you don't need to handle installing black, pylint or any other tool manually. You just need to install the `pre-commit` package and run `pre-commit run -a` which automates everything (installing tools, and running them with their specific configuration).

**Comment by jedwards4b** [comment]
In the current workflow if you push something that black doesn't like then you need to fix it locally and push it again.  So you need to download and run black on your local system.   I suppose you could do this without black locally but I would think that error prone.

**Comment by billsacks** [comment]
This is tricky. On the one hand, I agree with @jedwards4b that it's a bit annoying to need to remember to manually run black. And as a reviewer, it would be convenient if I could be assured that black has been run before I do any reviews. I also feel that, if we're going to use black, then we need to have 100% trust in it, so I have no objection to having it be run automatically on my code. (I don't think it would even work to review and back out changes that black has applied, even if you wanted to: if you do that, then the next time someone runs black, won't those changes just be reapplied automatically?)

However, I foresee a different set of problems if we have black run after you push your branch: I assume the workflow there would be: a GitHub Action runs and, if needed, makes a commit to your branch (under some name like "black"?) But then what happens back on the developer side? I think a likely scenario is that you then make some other changes to your code locally, try to push, and then find out that your branch is out-of-date because of these black changes that were applied server-side. So you need to fetch and pull/merge/rebase to bring your branch up to date before pushing. But due to the nature of black, it seems very likely that black's changes will result in conflicts with whatever you have changed locally, leading to a pain. (The most sane way to resolve this would probably be to ignore all of the changes coming from GitHub with an "--ours" merge strategy then let black get rerun, but that's only safe if you're positive that the only changes that have been made on the remote are from black, so it requires some checking each time it happens to make sure you're not discarding some real changes that should be applied.)

For these reasons, I think the best workflow would be one where black is run either automatically when you save the file (via editor integration - e.g., https://github.com/pythonic-emacs/blacken for emacs; I'm sure there are similar options for other editors) or via pre-commit hooks that people set up in their local cime clones.

(By the way, to continue to be a curmudgeon: These complications are why I'm not still convinced that black actually solves more problems than it creates.)

**Comment by jedwards4b** [comment]
Perhaps I just need to be clearer about the expected workflow.  I'm not sure that this was ever made clear.
Here is what I now do on cheyenne:  

> conda install pre-commit   (you only need this once)
> cd cime
> pre-commit run -a

This runs black and pylint locally and fixes any issues before you git push.   If you do this you should never see a pre-commit failure on github.

**Comment by rljacob** [comment]
Notes from telecon:  Our github hook is reporting errors but not fixing them. 
If we tell users to install git hooks (not github actions), those can make the changes. 
Black is fast but pylint takes about a minute.
pylint used to be slow because it launchd an instance for every file.
