### ISSUE TITLE
Set PIO_REARRANGER_LND to 2 for single point cases

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#4257]
We have found this needs to be set for NEON single point cases in ctsm5.1.dev095 which uses cime5.0.26. In some cases other single point cases already seem to have it set. It does seem to be required or the case will fail in some cases and in others just go really slow.

See the CTSM issue about this: 

https://github.com/ESCOMP/CTSM/issues/1743

We do have single point tests in the aux_clm test suite that seem to run fine without this being set.  See the ctsm5.1.dev096 tests for example on cheyenne under:

/glade/p/cgd/tss/ctsm_baselines/ctsm5.1.dev096/*1x1*

**Comment by ekluzek** [comment]
@jedwards4b do you have any thoughts on this? Does it make sense to you that this would be required for single point cases? Does this also mean this should be done for SCAM as well? Or any other single grid cell configurations?

**Comment by briandobbins** [comment]
My apologies - this was likely because we were trying to do something in
realtime, and Adrianna thought her run was going extremely slow.  I looked
at the dt in the log, it looked fast, and assumed, since this was a
single-core, NetCDF run, that perhaps the problem was the same as the NEON
runs.  Before I could investigate it further, there was an issue, and you
two digging into it, which I only saw after getting back from walking my
dog.

It seems this was a wild goose chase that I erroneously and unintentionally
sent you on!

  - Brian

**Comment by ekluzek** [comment]
We removed the use of this in CTSM in this commit, 

```
commit e855ee41a58a5033fc97adc531865635abbcace0
Author: Erik Kluzek <erik@ucar.edu>
Date:   Fri Nov 4 15:05:36 2022 -0600
```
So there seems to be no reason for this anymore. So closing as invalid.
