### ISSUE TITLE
updating pyCECT proceedure?

### ISSUE THREAD

**Issue by allibco** [ESMCI/cime#4262]
How does a new release of pyCECT get into CIME?  It looks like it is copied in as opposed to being grabbed from the repo:
https://github.com/NCAR/PyCECT/releases

I just want to make sure that the CIME version is up-to-date.

**Comment by jedwards4b** [comment]
I believe that its brought in as a git subtree - see the cime wiki.
https://github.com/ESMCI/cime/wiki/CIME-Git-Workflow#using-git-subtrees

**Comment by allibco** [comment]
Ok thanks.  It looks like I just need to do the "merging in changes from an external" workflow whenever there is a new pyCECT release.   So I'll see if I can follow those instructions :)

**Comment by allibco** [comment]
I haven't gotten this to work.  pyCECT is not in Externals.cfg - should it be?

**Comment by ekluzek** [comment]
@allibco  the things managed by "git subtree" aren't in the Externals.cfg file. I think this is all similar to how "manage_externals" is added to a repository which uses "git subtree". I have done that process before, but it looks like on cheyenne, you have to use an older version of git to have "git subtree" options available. You also might look into some of the documentation for manage_externals to see how it uses "git subtree" as it should all be the same type of process.

**Comment by fischer-ncar** [comment]
I used the following instructions for pycect and manage_externals updates.
https://github.com/ESMCI/manage_externals/wiki#including-manage_externals-in-other-repositories

**Comment by mnlevy1981** [comment]
Is there a reason pyCECT is included in CIME? Shouldn't it be in [ESCOMP/cesm](https://github.com/ESCOMP/cesm) since it's a CESM-specific tool? I would propose 

1. moving the contents of `tools/statistical_ensemble_test/` (except for the actual `pyCECT` subdirectory) to a new subdirectory in CESM (A top-level `statistical_ensemble_test/` directory? Or make a new `tools/` or `utils/` directory and then keep `tools/statistical_ensemble_test/`?)
2. adding pyCECT to CESM's `Externals.cfg`, perhaps with `required = False`.

The path to `cime/scripts` in `ensemble.py` and `single_run.py` would need to be updated, but that might be the only source mod necessary.

Besides seeming like a more natural home, it would be easier for @allibco to update the version of pyCECT in CESM as needed (she would just modify the tag in CESM's `Externals.cfg`).

If there's a good reason not to move the tool to CESM, could we at least remove the existing `pyCECT/` and add it to CIME's `Externals.cfg` file?

**Comment by allibco** [comment]
@mnlevy1981 This solution sounds good to me if others are ok with it.

**Comment by jedwards4b** [comment]
@allibco I think that this issue can be closed, please reopen it if there is anything unresolved.
