### ISSUE TITLE
github workflow e3sm tests failing 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#4399]
I believe that the solution is to add the  -fallow-argument-mismatch
to your gnu compiler flags.   We use this:

if (CMAKE_Fortran_COMPILER_VERSION VERSION_GREATER_EQUAL 10)
  string(APPEND FFLAGS " -fallow-argument-mismatch  -fallow-invalid-boz ")
endif()

in cmake_macros/gnu.cmake.

**Comment by jgfouca** [comment]
Hey @jasonb5 , can you add this to the macros? I'm not sure if this should go in cmake_macros/gnu.cmake, which would impact the entire project, or the macros you make for the VM that does the CI testing. I think I would prefer the latter?

**Comment by jgfouca** [comment]
@jedwards4b  , ah, I see. So this is necessary for things to work when gnu>=10. I will add it.

**Comment by jgfouca** [comment]
OK, PR for E3SM is up: https://github.com/E3SM-Project/E3SM/pull/5607

**Comment by jgfouca** [comment]
@jedwards4b , Jason and I found the problem which was a cmake_macro file that was added with the name gnu_docker.cmake. It was then inadvertently picked up by our github CI testing because we also use the machine name "docker" and the gnu compiler. I have renamed this file in E3SM and things should work now.
