### ISSUE TITLE
How to use case env variables during shell_commands testmods?

### ISSUE THREAD

**Issue by bartgol** [ESMCI/cime#4434]
The shell_commands script is run before case.setup, so the env variables are not yet available (in fact, `.env_mach_specific.sh` is not yet created). My goal is to do be able to have a shell_commands script like the following:
```
RUNDIR=$(./xmlquery --value RUNDIR)
mkdir -p ${RUNDIR}
cp ${MY_COOL_PATH}/some_file ${RUNDIR}/some_file
```
where `MY_COOL_PATH` is an env var for this machine, specified in the `config_machines.xml` file. E.g,
```
  <machine MACH="my_machine">
...
    <environment_variables>
      <env name="MY_COOL_PATH">/path/to/some/folder</env>
    </environment_variables>
  </machine>
```
Currently, my workaround has been to inject some XML parsing in the shell_commands script, to parse `env_mach_specific.xml` from the case dir, like so
```
RUNDIR=$(./xmlquery --value RUNDIR)
mkdir -p ${RUNDIR}
MY_COOL_PATH=$(python -c "
import xml.etree.ElementTree as ET
with open('./env_mach_specific.xml','r') as fd:
  tree = ET.parse(fd).getroot()
  env_vars = tree.find('environment_variables')
  my_path = [e.text for e in env_vars if e.attrib['name']=='MY_COOL_PATH']
  print (my_path[0])
")
cp ${MY_COOL_PATH}/some_file ${RUNDIR}/some_file
```
However, this is a bit involved, and I was hoping to avoid manual parsing of XML scripts.

One possibility I thought of: make shell_commands run also after case.setup (and maybe after case.build?), and have CIME provide an env var to tell shell_commands what phase it's in. So I could do something like this
```
if [ "${CIME_SHELL_COMMANDS_PHASE}" = "post-setup" ]; then
  RUNDIR=$(./xmlquery --value RUNDIR)
  mkdir -p ${RUNDIR}
  cp ${MY_COOL_PATH}/some_file ${RUNDIR}/some_file
fi
```
I realize however that this may not be bwd compatible, since shell_commands would have to run 2+ times, and some existing shell_commands files may be performing actions that cannot (or should not) be run twice (perhaps create a file, which may cause nonzero ret code if run twice). Maybe we could have CIME query for a different filename after setup phase. Something like `shell_commands_post_setup` maybe?

**Comment by jedwards4b** [comment]
Including some conversation from spack:

Luca Bertagna
 
[9:29](https://cime.slack.com/archives/C0J7HLZA9/p1685114953405609)
question: how come shell_commands runs before everything else? what's the use case behind that choice? I would have assumed that any testmod one could do would not change the machine settings, so that shell_commands could be easily run after bld/, run/, and .env_mach_specific.sh are created...


Rob Jacob
  [9:43 AM](https://cime.slack.com/archives/C0J7HLZA9/p1685115808622599)
We’re talking about shell commands in a test mod ?


Luca Bertagna
  [9:51 AM](https://cime.slack.com/archives/C0J7HLZA9/p1685116274781319)
yes
[9:51](https://cime.slack.com/archives/C0J7HLZA9/p1685116313800129)
I need to copy some files from a certain folder to the run dir


Jim Edwards
  [9:54 AM](https://cime.slack.com/archives/C0J7HLZA9/p1685116449586979)
@ibertag - it's a good question I thing that some changes you may do in shell_commands require case.setup to be rerun but perhaps we can change the implementation order and just run case.setup twice - once before and once after running shell_commands
New


Luca Bertagna
  [9:58 AM](https://cime.slack.com/archives/C0J7HLZA9/p1685116720107849)
I guess sandwiching with case.setup around shell_commands is safer than the other way around. I guess the 2nd case.setup should be a case.setup --reset, just in case shell_commands changed some key machine/compiler setting?


Jim Edwards
  [10:01 AM](https://cime.slack.com/archives/C0J7HLZA9/p1685116883428479)
yes

**Comment by billsacks** [comment]
A few replies:

> question: how come shell_commands runs before everything else? what's the use case behind that choice?

Some historical context: I think the original vision for this was a simple list of xmlchange commands without any logic. With that vision, you might as well run this right after case creation. In fact, this file was originally called xmlchange_commands, but then we realized that the implementation allowed for more generality, so we generalized the name to shell_commands, though (I think) without having a clear vision of how people might want to use this more generally beyond the original simple list of xmlchange commands.

Another reason for the timing of its application was convenience: shell_commands and user_nl files are copied into the case upon case creation, so this was a convenient time to execute the shell_commands file as well.

> I realize however that this may not be bwd compatible, since shell_commands would have to run 2+ times, and some existing shell_commands files may be performing actions that cannot (or should not) be run twice (perhaps create a file, which may cause nonzero ret code if run twice). Maybe we could have CIME query for a different filename after setup phase. Something like shell_commands_post_setup maybe?

I agree that we should avoid running shell_commands multiple times. I like the idea of having a completely different file for shell commands that need to be run post-setup: this feels like the most explicit and least complex solution and keeps things working the same as they are now in the typical case where shell_commands can safely be applied before setup.

Another point to keep in mind here is that this implementation is used not just for tests but also for standard cases (via the general usermods functionality); for those, the user has control over when case.setup is run and possibly rerun (and rerun, and rerun...). Some thought may be needed as to when you would execute the shell commands in that situation.

@ekluzek @adrifoster @samsrabin I feel like you have all been thinking about shell_commands recently, so looping you into this.

**Comment by samsrabin** [comment]
When I was first writing my prescribed crop calendars test (before switching to a SystemTest) I think I remember also being vexed by the timing of `shell_commands`, so I support the idea of a separate post-setup version.

**Comment by ekluzek** [comment]
Hmmm, we do have some uses of ./xmlquery in shell_commands in some of our use-cases. I think you are right though that you don't have access to everything because it's before case.setup. But, here's an example where we query the compset (since that's available at this point).

https://github.com/ESCOMP/CTSM/blob/master/cime_config/usermods_dirs/NEON/defaults/shell_commands

But, I think I also agree with @samrabin that maybe having a post-setup version could be helpful in some cases. Maybe you have

`./shell_commands`

And then optionally have

`./post_setup_shell_commands`

that's run after setup. Since post_setup_shell_commands are optional, the current test mods would all work as they are. But, then we can start adding things that have to happen after you run case.setup.

**Comment by bartgol** [comment]
I agree, a separate optional script for post-setup mods seems the most robust, easy, and bwd compatible approach.
