### ISSUE TITLE
gen_domain uses non-standard fortran extensions that don't work with all compilers

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#4455]
A user ran into trouble compiling gen_domain with some version of gfortran because of the use of iargc, which is a non-standard Fortran extension. It worked when the user changed iargc to command_argument_count, which is the newer Fortran standard method. I also suggested replacing the uses of getarg with get_command_argument, but I don't think that turned out to be needed  for that user.

I started to make these changes and test them, but ran into trouble building gen_domain on my local machine. Before we spend time patching this, I first wanted to check whether this is something that is still being used by either CESM (@jedwards4b , @ekluzek do either of you know?) or E3SM (@rljacob @jgfouca @jasonb5 do any of you know?).

**Comment by ekluzek** [comment]
gen_domain is largely deprecated, in CESM because you don't need domain files anymore with NUOPC. It would only be required for MCT, which is now deprecated.

I think it's possible there might be really limited applications where gen_domain could be useful. The only thing that comes to mind is that we are using domain files in CTSM to create mesh files for subset_data. But, that's only used for a standard grid, so there's no reason to use gen_domain on a new grid.

So although gen_domain was a workhorse application in the past, it's not required anymore and as such doesn't make sense to put a lot of effort into it.

**Comment by billsacks** [comment]
Thanks @ekluzek . Based on your input, I'm doing the quick fix that I had already determined, testing it on cheyenne, but I'm not tackling the more open-ended issue of getting the gen_domain build to be more robust.
