### ISSUE TITLE
Request update for create_ESMF_map.sh on Derecho

### ISSUE THREAD

**Issue by fzhu2e** [ESMCI/cime#4489]
The current `tools/mapping/gen_mapping_files/gen_ESMF_mapping_file/create_ESMF_map.sh` doesn't support Derecho, the new NCAR machine.

With my personal trial of loading ESMF 8.4 and 8.5 on Derecho, it leads to inconsistent and wrong results compared to those on Cheyenne.

Furthermore, with a test of ESMF 7.1.0r on Cheyenne, I found that the `mpiexec` and `--serial` modes lead to inconsistent results, and the `--serial` mode yields wrong results, which seems strange.

**Comment by jedwards4b** [comment]
I understand why mpiexec and --serial yield different results - but what is the basis for the claim that --serial is incorrect?  Also did you try this with newer versions of ESMF on cheyenne?  for example esmf-8.5.0?

You also suggest that esmf 8.5.0 on derecho is "inconsistent and wrong results compared to those on Cheyenne."   Please provide evidence for this declaration.

**Comment by fzhu2e** [comment]
Hi Jim, thanks for the prompt reply! It could be that I wasn't loading the modules properly, which is why I made this request of an official update of the script.

I will streamline a clean and reproducible test later and post it here.

**Comment by fzhu2e** [comment]
Hi Jim @jedwards4b  and Michael @mnlevy1981 , 

This notebook (https://gist.github.com/fzhu2e/08193085cb5def210d1dd7beeb28b5da) illustrates the ESMF regridding inconsistency between Derecho and Cheyenne. 
It can also be accessed on Derecho at: /glade/work/fengzhu/Projects/test_ESMF_Derecho/compare_mappings.ipynb

Please let me know if my module loading is problematic, and if you have any thoughts.

Thanks,
Feng

**Comment by billsacks** [comment]
@fzhu2e - thank you for raising this and for your careful analysis.

There have been numerous changes to ESMF between versions 7.1.0r and 8.5.0. Some of these changes are expected to change answers for regridding: see https://earthsystemmodeling.org/static/releases.html and search for "bit-for-bit" in the release notes. I see that one change (in the ESMF 8_1_0 release notes) can change the number of points in the mapping matrix for some cases - though it sounds like the expectation from that change is that the new mapping matrix can contain more points, whereas you're seeing fewer with the new mapping, so that may not be the cause of that difference you're seeing. In general, though, I'm not surprised to see differences when changing ESMF version, compiler and machine.

If it's feasible, it could be helpful to dig into the case where you show a different size of the S matrix - finding the point that exists in one but not the other (based on the row / col values) and its S value. But I'm not sure if this is worth the effort given that the most likely outcome will be to find that the difference is expected, and it could take a lot of effort to get to that point.

The difference between the parallel and serial cases does look large. One thing to confirm is whether the row and column values are in the same order for the parallel and serial cases; if not, that would explain the differences you're seeing by just comparing the S matrices. If the row and column values are in the same order in both and you're seeing large differences in the S matrices, then it would be great if we can reproduce this through direct calls to ESMF_RegridWeightGen that could then be sent to the ESMF team.

**Comment by jedwards4b** [comment]
I see that on derecho you are using intel-oneapi/2023.0.0 which uses the ifx compiler instead of ifort - can you try again using intel/2023.0.0 instead?

**Comment by mnlevy1981** [comment]
In line with what @billsacks said, I don't think it makes sense to compare the mapping matrices themselves -- I would be interested mapping the same field from the source grid to the destination using both maps, and then comparing the fields on the destination map to determine how different the maps are. We have [tools to do that](https://github.com/ESMCI/cime/tree/master/tools/mapping/map_field), although it has been a while since I've looked at the `map_field` utility so I don't know if it needs work before it builds on derecho (you should be able to build it on cheyenne, though)

**Comment by fzhu2e** [comment]
Thank you all @jedwards4b @billsacks @mnlevy1981 for the timely information, and for the helpful test by Jim with the `check_map` tool: https://gist.github.com/fzhu2e/08193085cb5def210d1dd7beeb28b5da#gistcomment-4699797

So you're suggesting that even the mapping matrices look different in values and sizes, it won't affect the correctness of the mapped results. I find this surprising but I believe you are right on this.

The initial motivation of my request is that in my deep time CESM simulation, I got segmentation fault after only several model steps, and when I checked the TS field in the output, there were gridpoints with values ~30 K on the coastlines, which made me thought there were some mapping issues.

<img width="950" alt="image" src="https://github.com/ESMCI/cime/assets/1380844/cc12816b-6c72-4c25-9f3f-6c87861ac0a9">

I'll check if other issues cause the problem. Thanks again for your timely help!
