### ISSUE TITLE
Make default for one PE cases to use mpi-serial MPILIB

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#506]
The behavior for cime4 was that a case using only one total task would default to using mpi-serial for MPILIB. In cime5.0.9 this isn't the case. Since, running without a MPI library is so much simpler this is a nice behavior to have. Running with 1 task with MPI is of course possible, but it's nice to make the default to use mpi-serial.

In cime4 this behavior was overridden in create_newcase itself, which isn't a great way to do this.

**Comment by rljacob** [comment]
We changed this because the mpi libraries available on a machine are supposed to be specified in config_machines.xml.  If mpiserial is not there, create_newcase should not force it under the hood.

We found a couple of machines where mpiserial does not build/work (Titan, Mira) and no one had the cycles to debug it so its easier to remove it as a requirement for CIME.
