### ISSUE TITLE
PET tests do not work on skybridge

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#539]
Skybridge insta-fails the single-threaded case because it tries to use 16 procs-per-node and the sbatch only requested 8 ppn.

**Comment by rljacob** [comment]
The key insight on this issue was from @jedwards4b "this test should not change NTASKS because some components which are not bfb with different number of mpi-tasks can still pass a test with different numbers of threads".   CIME5 had done that which also broke things on skybridge.  Need to change it to keep mpi-tasks constants.

**Comment by jgfouca** [comment]
@rljacob that's not quite true. CIME5 was leaving NTASKS the same. The only error was the increase in the PPN flag provided to mpiexec which happened in CIME5 and not CIME4 because CIME5 computes the mpiexec command on-the-fly.
