### ISSUE TITLE
RMS failures in tests should be reported *concisely* in TestStatus.log

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#566]
In cime4, RMS diffs were reported in TestStatus.log. That functionality should be brought back.

**Comment by billsacks** [comment]
Never mind, this functionality is still there.

**Comment by billsacks** [comment]
I am reopening this with a different name: Apparently the current behavior is to echo the entire cprnc output file to TestStatus.log. I feel it would be more useful to go back to the old behavior where just the RMS lines were echoed to the TestStatus.log file, to avoid overwhelming that file and making it hard to skim through.

Ideally it would also have the last few lines of the cprnc output, which give the final summary of results.

The point of this functionality, as I see it, is for tests where you just expect a few fields to differ - so for this main use case, it's better to have just a concise summary for the sake of keeping TestStatus.log human-readable.

**Comment by billsacks** [comment]
Tagging @mvertens @ekluzek and @fischer-ncar

**Comment by ekluzek** [comment]
In my testing with cime5.1.1 I don't see any part of the cprnc output echoed to the TestStatus.log file. And although it reports on what files it's comparing it doesn't seem to report if a comparison was an unexpected difference.

**Comment by jedwards4b** [comment]
@ekluzek can you point me to a case where you expect something in TestStatus.log but it's not there.

**Comment by ekluzek** [comment]
For example this test on hobart...

/fs/cgd/data0/erik/clm_esmciport/cime/scripts/ERS_D_Ld5.f10_f10.ICLM45ED.hobart_nag.clm-edTest.C.20160921_014124

TestStatus shows...

FAIL ERS_D_Ld5.f10_f10.ICLM45ED.hobart_nag.clm-edTest COMPARE_baseline

In TestStatus it reports on files it's comparing as in...

  comparing model 'clm'
    /scratch/cluster/erik/ERS_D_Ld5.f10_f10.ICLM45ED.hobart_nag.clm-edTest.C.20160921_014124/run/ERS_D_Ld5.f10_f10.ICLM45ED.hobart_nag.clm-edTest.C.20160921_014124.clm2.h0.0001-01-01-00000.nc.base matched /scratch/cluster/erik/ERS_D_Ld5.f10_f10.ICLM45ED.hobart_nag.clm-edTest.C.20160921_014124/run/ERS_D_Ld5.f10_f10.ICLM45ED.hobart_nag.clm-edTest.C.20160921_014124.clm2.h0.0001-01-01-00000.nc.rest
  comparing model 'sice'
    no hist files found for model sice
  comparing model 'socn'
    no hist files found for model socn

But, it doesn't report if the comparison was successful or not. I'd like to have it report the result of the comparison.

OK, I thought I wasn't seeing the cprnc.out results, but after a careful look through all my cases, the only reason for my comparison fail's is because of missing baseline files. So I take back my report that the cprnc output isn't there. It looks like it's not there when the comparison is exact. I would still like it to report on the results of the comparison it does do, including saying that a comparison was identical. But, I don't have an example of one with a difference where it didn't include the cprnc output. Sorry about that.

**Comment by ekluzek** [comment]
OK, I now have a test with different answers, and it has the entire cprnc.out difference in the TestStatus.log as advertised. This helped me to easily find the difference. I do still agree with Bill, that I'd rather have a summary of the difference, showing the RMS differences and the tail summary of cprnc. And I'd like a confirmation that files were compared and are identical when that happens as well.
