### ISSUE TITLE
Don't rebuild namelists if you don't have to

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#650]
If namelists, XML, and sourcemods have not changed, do not rebuild namelists because it's somewhat expensive and produces lots of output.

**Comment by jgfouca** [comment]
@jedwards4b @mvertens I'm starting to wonder if this change is worth the trouble. It looks like 4 calls to preview_namelists are made for a basic case:
- case.setup
- build model
- case.submit
- case.run

If any change to any XML file could potentially impact preview_namelists, then I have to add all the env_*.xml files to the checksum. Then the problem is that most of the steps above make at least one change to the XML, so we'll end up rebuilding the namelists over and over and won't gain anything from this change.

My profiling indicates that preview_namelists takes about 10 seconds on a very fast machine. So based on the list above, that's about 40 seconds total for previewing namelists per case. On this machine, our cime_developer test cases take 2-3 minutes total, so about 1/4 of that runtime is preview_namelists. This is obviously not going to have any impact on a large case, but this probably is having some impact on the turnaround time for scripts_regression_tests.

Part of my frustration here is that namelist-related code makes up thousands of lines of python in CIME and my understanding both of the code and the concepts behind it are very limited. It would help if I understood the following:
- Conceptually, what is a namelist?
- When is the data contained in namelist files used?
- What determines if data should be represented in a namelist vs. XML?
- What assumptions can we make about a component's namelists? Are component buildnml programs always going to be in python? If so, could we access them via library instead of shell command?

**Comment by gold2718** [comment]
I'll take a crack at these questions:

_Conceptually, what is a namelist?_
A namelist is input data to a Fortran program, however, rather than being passed on the command line, it is read using the special Fortran namelist construct. This allows variables to have defaults in the code (only variables found in the namelist file being read are changed), however, we are trying to move away from having defaults in the code.
The namelist also serves a provenance function in that it documents the actual code paths and tuning parameters used. This is why we need to move away from code defaults.

_When is the data contained in namelist files used?_
Each model typically reads its namelist information early in its initialization sequence. This would apply to all run types (initial, branch, restart). These variables control everything from decomposition to details of the science run (e.g., convection tuning parameters).

_What determines if data should be represented in a namelist vs. XML?_
Any input data to a model eventually needs to end up in that model's namelist. Most of the data starts off in some XML file (e.g., a case XML file or a model's namelist_definition.xml or a use case file).

_What assumptions can we make about a component's namelists? Are component buildnml programs always going to be in python?_
Unfortunately, most of the model namelist-building code is still in perl. python seems like a good choice for moving forward. Conversion of some of them is hard (e.g., CAM) because way too much logic is in the script instead of the namelist_definition.xml

_If so, could we access them via library instead of shell command?_
Eventually?

**Comment by billsacks** [comment]
@jgfouca - part of the problem, which you allude to, is that we regenerate namelists in each phase from case setup through run - i.e., your list:

- case.setup
- build model
- case.submit
- case.run

As far as I know (which may be wrong), this aggressive regeneration of the namelists isn't necessary for the correct operation of the system. Rather, I'm _guessing_ it was put in place for the sake of a (perceived) convenience for the users: ensuring that the generated namelists are kept up-to-date.

I'd suggest that the low-hanging fruit here is to _not_ regenerate namelists at all of these stages. I'd suggest that namelists be regenerated during:

- case.setup: this is useful so that the user has an initial version of the namelists to examine... though I think even this isn't strictly necessary
- case.run: my sense is that this is the only one that is strictly necessary

I'd especially like the regeneration of namelists to be removed from case.build, because this really slows things down when you're trying to iteratively fix compilation errors. (Or, if people really want namelists to be regenerated during this phase, it should be done _after_ the compilation step, not before it.)

Users can always force the regenation of namelists by running preview_namelists.

**Comment by ekluzek** [comment]
I think I agree with Bill here, that the namelists don't really have to be constantly regenerated. 

But, I do want to point out that another function is the prestaging of data which is corrected when the namelist is updated. I typically see datafiles brought in from svn inputdata at the build step. So if you remove namelist generation from build, you should also remove the check_inputdata step from there. But, then when would the prestaging step happen?

Along the same lines, the reason to run the prestage at submit time, is to catch errors that you might have introduced. And I would rather that previewnamelist be run at this point to catch an error, rather than submitting to the queue and not finding out until after you get into the queue which may be a long wait.

That's why it would be best if it could detect if the namelist regen really needed to happen or not.

**Comment by billsacks** [comment]
@ekluzek - I see your points about doing the error-checking earlier rather than waiting for the run to start.

It still seems like it could make sense to Would a compromise be to remove namelist generation and data prestaging from the build phase, because there is no reason to expect the various runtime inputs to be in their final state at this point. Could data prestaging be moved to the submit stage?

**Comment by rljacob** [comment]
I think the XML vs. namelist distinction is:  If its a variable that CIME needs to know about or coordinate between two models (like the stop time) then its in XML.  Otherwise, its only in the namelist format. 

True or False:  Every XML variable winds up being part of one or more namelists.

**Comment by billsacks** [comment]
In addition to @rljacob 's points:

> If its a variable that CIME needs to know about or coordinate between two models (like the stop time) then its in XML

I'd add: Some XML variables are only needed by a single model, but are responsible for setting multiple namelist defaults in that model.

**Comment by jedwards4b** [comment]
Not all XML variables end up as namelist variables.   For example DOUT_S controls whether or not the st archive script is run and does not end up in any namelists.
