### ISSUE TITLE
Move component-specific tests out of CIME

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#651]
LII and SSP should not be under CIME

**Comment by ekluzek** [comment]
Hi @rljacob. So is it possible to put them underneath a specific component's cime_config directory? Where do they go and how do they get hooked up into the system? This wasn't possible in the past. If it's possible now, I'm happy to have them moved. These two are very specific to CLM.

@billsacks @bandre-ucar @mvertens

**Comment by billsacks** [comment]
@jedwards4b started working on a solution for this. I agree these should be moved out of cime, but  there were two pieces of robustness that I felt needed to be added before I was comfortable with moving these tests to the components:

1. Rather than taking the first instance of a given test found in any component, look for the given test in ALL components, and raise an exception if a test with that name is found in more than one place

2. Some scheme for having the relevant pieces of config_tests.xml also distributed to the components, so (e.g.) the LII test doesn't need to be defined at all in cime, but rather can live completely in CLM.

**Comment by billsacks** [comment]
Thinking about https://github.com/ESMCI/cime/issues/651#issuecomment-252348999 a bit more: I imagine that point (1) is easy, but point (2) is hard. But that led me to wonder: Why do we have config_tests.xml anyway? Personally, I find it confusing that some aspects of test configuration information appear in this xml file, and other aspects appear in the python code: it means you need to look in two places to completely understand how a test is set up.

So I'd vote for the removal of config_tests.xml, at which point it should be relatively easy to move component-specific tests into their component.

From a very quick look through config_tests.xml, it seems we have a few types of things set there:

(1) Settings that most test types want, like setting INFO_DBUG=1. These should probably be set by SystemTestsCommon, with optional constructor arguments that allow individual test types to override the default behavior.

(2) Settings of the default run length. These could be handled by forcing tests to be explicit about their length (e.g., DAE_Ld4). If people don't like that, then these could be handled like (3).

(3) Test-specific settings, like setting BFBFLAG=TRUE for ERP. These should probably be set in the python code.

**Comment by ekluzek** [comment]
Hmmm. I'm not completely convinced here. I do see the point about needing to see both config_test.xml and the Python code, and having to only look at one or the other would be prefered. But, part of the move you are suggesting is to change what's currently in XML to be hardcoded in Python. As a general rule I think the XML data side is easier to understand. So if you want to move between XML and Python I'd encourage it to be moved more to XML rather than Python. But, that's a general rule of thumb, I could be convinced that doesn't apply in this case.

I do think that your idea of requiring the run length to be given in the test name is a good one though. That just makes the test and what it does more explicit in it's name, which is a good thing anyway. This would require everyone to go through their testlists and add an explicit length, which would be a pain to get everyone to do.

**Comment by billsacks** [comment]
@ekluzek - I see your point. To record what we talked about in person: If we could completely specify a test via xml, that would be great, but since we can't, we need to at least partially specify it via python anyway. I see:

Best: Specify tests via xml or some other data-driven approach

Next best: Specify tests via code, all in one place

Third best (i.e., worst): Specify tests partially via code, partially via data

Part of my reasoning here is: I know there has been a lot of confusion in the past when new people try to understand and modify tests, or write new tests, caused by the fact that you actually need to look in two different places to understand any given test.

That said, I don't feel super strongly about this, and am also open to keeping tests partially specified in config_tests.xml if we change the code so that it looks for a config_tests.xml in the components' directories as well (or something like that).

As to this:

> This would require everyone to go through their testlists and add an explicit length, which would be a pain to get everyone to do.

I agree. A migration path forward could involve temporarily setting default test length in the code, like other things are set.

**Comment by jedwards4b** [comment]
The idea of config_tests.xml is that it allows the user to change fields in the xml files of a test without unintentionally changing fields that the test itself depends on.  If a user needs to change a field the test depends on they need to explicitly make the change in env_tests.xml instead of the default case xml file.   Your proposal of moving these fields from xml into python would require a user to modify python if they wanted to modify a test.  I find this unacceptable.

**Comment by billsacks** [comment]
> The idea of config_tests.xml is that it allows the user to change fields in the xml files of a test without unintentionally changing fields that the test itself depends on.

Thanks for providing this rationale - this makes sense. So you're saying that something in the scripts prevents a user from overriding things like HIST_OPTION / HIST_N?

That doesn't necessarily argue for having this in xml, though: it seems the same affect could be achieved by having a case.set_value call in the python. Which brings us to:

> Your proposal of moving these fields from xml into python would require a user to modify python if they wanted to modify a test.

It seems to me that there are very few useful changes you can make to a test just by changing the xml file.

But I don't want to spend a lot of energy arguing this point. If people feel strongly about maintaining the xml file, I'm okay with that for now.

**Comment by jedwards4b** [comment]
As a fairly frequent example

 HIST_OPTION=nsteps, HIST_N=1, STOP_OPTION=nsteps, STOP_N=3

I do this or something similar frequently in test cases and don't want to have to build another case to do it.   Currently I can change these fields in env_test.xml and continue using the same case.

**Comment by billsacks** [comment]
The STOP_* pieces can be achieved by adding _Ln3 to your test case (e.g., ERS_Ln3...). I hadn't thought of the HIST_OPTION/HIST_N use case - thanks for providing that example.

**Comment by billsacks** [comment]
As I think more about what things will look like when tests are distributed to components, I feel it's important that settings that need to be done for nearly all tests – like setting INFO_DBUG=1, DOUT_S=FALSE, HIST_OPTION=$STOP_OPTION, HIST_N=$STOP_N – should appear in one and only one place. For example, there could be a defaults section in config_tests.xml and these could appear there.

The reason is: If these general needs change, or there is a new variable that needs to be set for all tests, we don't want to have to make this change in every component that defines its own tests.

**Comment by jedwards4b** [comment]
I would prefer to resolve these issues before adding any more component specific tests!
