### ISSUE TITLE
mpi-serial not working on anlworkstation

### ISSUE THREAD

**Issue by sarich** [ESMCI/cime#667]
Using mpi-serial, the netcdf library has an unresolved depency on MPI_File_open

**Comment by jayeshkrishna** [comment]
This fell off my radar. I will try a build on anlworkstation with mpi-serial to reproduce this issue.

**Comment by jayeshkrishna** [comment]
So apparently the issue is that the wrong netcdf library is included for anlworkstation in the mpi-serial case.
Currently parallel versions of hdf5 and netcdf are loaded for all mpilibs (including mpi-serial). If the serial version of netcdf library (and no hdf5 required here) is included for mpi-serial builds the build completes successfully. The parallel versions of netcdf library require mpi_file_open() but serial versions do not.
I will create a PR soon.

**Comment by jayeshkrishna** [comment]
Unfortunately we don't have the soft env key for the netcdf serial libs. I will ping systems about it.

**Comment by jayeshkrishna** [comment]
This issue will be fixed after resolving Issue #1033 (a separate issue that needs to be fixed for building CIME on compute001)

**Comment by jayeshkrishna** [comment]
The soft key +netcdf-4.4.1c-4.2cxx-4.4.4f-serial-gcc6.2.0 is now available on compute001 .

**Comment by rljacob** [comment]
Was this fixed?

**Comment by jayeshkrishna** [comment]
No, this was kept on hold due to the recent CIME merge (reorganization of the source tree etc). I will fix this on the ACME side today.

**Comment by jayeshkrishna** [comment]
This ACME-specific issue is being handled in ACME-Climate/ACME#1504 . Should be brought in to ESMCI/cime in the next ACME->CIME sync.
