### ISSUE TITLE
xmlquery should give more info

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#767]
Currently if I run xmlquery PIO_TYPENAME I get:
```
PIO_TYPENAME	pnetcdf	type:char
		pio io type
```
what I would like to see by default is the full xml entry:
```
    <entry id="PIO_TYPENAME" value="pnetcdf">
      <type>char</type>
      <valid_values>netcdf,pnetcdf,netcdf4p,netcdf4c,default</valid_values>
      <desc>pio io type</desc>
    </entry>
```

**Comment by billsacks** [comment]
I'd vote for different levels of verbosity:

1. Just give the current value

2. Give the current value & description

3. Give the full metadata, including the type and valid_values

Personally, I generally want (1), so would argue for that as the default, but don't have strong opinions on that.

**Comment by ekluzek** [comment]
I agree with @billsacks I'd like to have a less verbose level to be the default (I'd probably pick 2 from Bill's list above). But, I do like the idea of different options. I do see where seeing the full XML entry could be useful especially as we add metadata, xmlquery might not be caught up the ability to parse new metadata. But, I would say showing the XML entry would be an option you pick rather than the default.

Although I'm pretty sure there already are options that do Bill's list right now, but they are separate options, so not as obvious as his list. A new capability would be to add the XML entry.

**Comment by jedwards4b** [comment]
There is not an option to spit out the full xml, I don't care if thats the default or not.  Currently the fields output by xmlquery are hardcoded - it's only looking for a few fields it expects to find.  There is no reason to do that it should be an inspector for the entire entry.

**Comment by billsacks** [comment]
My main original point was just to make sure that the full verbosity wasn't going to become the default, because I would find that overwhelming as a user.

But I'd also say that the current default behavior is still too verbose; e.g., for STOP_N:

```
./xmlquery STOP_N
run_begin_stop_restart:STOP_N	5	type:integer
		       Provides a numerical count for $STOP_OPTION.
```

I'd at least get rid of the 'run_begin_stop_restart' and 'type:integer' in the default output. But that's just my opinion; happy to be overruled here.
