### ISSUE TITLE
Small differences in A-cases between cime2 and cime5

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#837]
In our testing with CIME5 in ACME, comparisons with cime2 baselines for A-cases report very small differences in 3 fraction variables:
fraca_ifrac, fraca_ofrac and fraca_lfrac
each with an "rms diff" of around 1.0E-17.

We can easily bless those diffs, especially since I verified no diffs in an F and B case, but it would be good to know what caused those.  Any ideas?

**Comment by rljacob** [comment]
This turned out to be caused by different PE layouts.

**Comment by ekluzek** [comment]
Don't data components preserve answers for different PE layouts? Or is this
due to some with threading and some not?

I'm concerned if data models aren't preserving answers for difference in
tasks.

*Erik Kluzek, (CGD at NCAR)*

*National Center for Atmospheric Research*

*Boulder CO, *

*(off) (303)497-1326 (fax) (303)497-1348*

*(skype) ekluzek    (cell) (303)859-0183*

*Pronouns: he/his/him*

*------------------ Home page ------------------------*

*          http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*

*          https://staff.ucar.edu/users/erik
<https://staff.ucar.edu/users/erik>*

*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*

**Comment by rljacob** [comment]
The mapping may generate different answers if BFBFLAG is false (which is was).
