### ISSUE TITLE
Can we get more detailed timing information back in CESM?

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#938]
In recent versions of cime, the default timing information is very coarse-grained, and thus not really useful for looking at timings of individual pieces of code. At a recent CSEG meeting @jedwards4b said he thought that there might be more timing information by default in a CESM case, but as far as I can tell that isn't true. Can this be made true - i.e., we go back to having the default, more detailed timing information in CESM? Or are there reasons why this is bad (performance, etc.)?

 e.g., from this test from master: `SMS.f45_g37.A.yellowstone_intel` - all we get is now:

```
name                  processes  threads        count      walltotal   wallmax (proc   thrd  )   wallmin (proc   thrd  )
"CPL:INIT"                   15       15 3.000000e+01   3.868827e+02    25.798 (     6      0)    25.786 (     0      0)
"CPL:RUN_LOOP_BSTART"        15       15 1.500000e+01   3.476910e-03     0.000 (    13      0)     0.000 (     7      0)
"CPL:RUN_LOOP"               15       15 3.600000e+03   2.157233e+02    22.350 (     1      0)    10.397 (     5      0)
"CPL:CLOCK_ADVANCE"          15       15 3.600000e+03   5.310138e-01     0.038 (     4      0)     0.031 (     5      0)
"CPL:RUN"                    15       15 3.966000e+04   2.044285e+02    21.629 (     1      0)     9.563 (    11      0)
"CPL:COMM"                   15       15 1.446000e+04   1.597295e+00     0.196 (    11      0)     0.059 (     0      0)
"CPL:ICE_RUN"                15       15 3.600000e+03   3.956535e+00     0.289 (     1      0)     0.230 (    14      0)
"CPL:ROF_RUN"                15       15 3.600000e+03   2.464620e+00     0.170 (     0      0)     0.162 (    12      0)
"CPL:ATM_RUN"                15       15 3.600000e+03   2.480473e+00     0.190 (     0      0)     0.159 (     4      0)
"CPL:TPROF_WRITE"            15       15 3.600000e+03   4.331141e-04     0.000 (     1      0)     0.000 (     8      0)
"CPL:C2O_INITWAIT"           15       15 6.000000e+01   6.367750e-03     0.001 (    10      0)     0.000 (     2      0)
"CPL:OCN_RUN"                15       15 6.000000e+01   2.263431e-02     0.002 (     0      0)     0.001 (    14      0)
"CPL:RUN_LOOP_BSTOP"         15       15 1.500000e+01   1.195260e+02    11.952 (     3      0)     0.000 (     1      0)
"CPL:FINAL"                  15       15 1.500000e+01   3.780562e-02     0.003 (    10      0)     0.003 (     3      0)
"final:t_prf"                 0        0 0.000000e+00   0.000000e+00     0.000 (     0      0)     0.000 (     0      0)
```

And we only get that level of detail from an I case as well (I case tested with beta04 version of cime).

cc @sherimickelson @jedwards4b

**Comment by worleyph** [comment]
The default DETAIL was set to zero. It should be at least 1, and I prefer 2. With the new prefix logic, it can go higher (to show off intialization cost details) without confusing intialization and run loop timers. I typically run with 8 these days (because initialization has become a problem on some systems, but that is just me).

**Comment by jedwards4b** [comment]
@worleyph aren't you the one that set the default to 0?   Can we change it to 2?

**Comment by worleyph** [comment]
@jedwards4b , I don't believe that I touched this, at least not deliberately. First thing I did on the ACME side was request that it be set to 2. I redefined what '0' meant (to be the minimum), but did not do anything with the defaults.

**Comment by worleyph** [comment]
I was referring to the defaults in env_run.xml . The defaults in perf_mod are likely to be ignored. Perhaps this is where this crept in? In any case, I vote for setting the default to be 2, by whatever mechaism, but this enables full atmospheric physics timing. Others have preferred to throttle this in the past, and they should speak up.

**Comment by jedwards4b** [comment]
Okay then, I will change it to 2.

**Comment by ekluzek** [comment]
All note, that there seems to be a bug in at least older versions of CIME
where TIMER_DETAIL isn't listened to. So it defaults to 0, unless you add

profile_detail_limit =

into your user_nl_cpl.

Also can someone explain the difference between TIMER_DETAIL and
TIMER_LEVEL -- and add it to the documentation?

*Erik Kluzek, (CGD at NCAR)*

*National Center for Atmospheric Research*

*Boulder CO, *

*(off) (303)497-1326 (fax) (303)497-1348*

*(skype) ekluzek    (cell) (303)859-0183*

*Pronouns: he/his/him*

*------------------ Home page ------------------------*

*          http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*

*          https://staff.ucar.edu/users/erik
<https://staff.ucar.edu/users/erik>*

*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*

**Comment by worleyph** [comment]
@jedwards4b , thanks.

**Comment by worleyph** [comment]
@ekluzek , 

a) depth is easy - how many levels of nested timers to record.

b) detail is more fluid. There are explicit 'detail_adj' commands in the code that increase or decrease the detail limit associated with any timer following the adjust commands. This is used to control what timers are enabled (structurally, rather than call stack depth), and was originally put in to disable some low level timers in the atmospheric physics, and also to disable timers in the initialization (since this called run phases ATM, and other?, components, and things got very confused).

Currently:

'0' is the minimum for the performance summarization script to work (primarily CPL:xxx timers).
'1' is what CESM used to prefer, with some details missing in the physics.
'2' is the current ACME default, which enables all timers in the Run Loop, but not many in the initialization

Since component run phases are called during initialization, there is a multiple of two issue in getting all initialization timers enabled. '4' should be enough for most things, but it isn't (8 is enough to get everything). I'll run a few experiments and nail down these details. Since I put timers in MCT and PIO (for example), some of what I remember may be peculiar to me. I'll make sure to use an unmodified version of the model.

BTW - if no one cares about disabling the low level atmospheric physics timers, then we could probably simplify this somewhat.
