### ISSUE TITLE
check_input_data doesn't find / download files needed by the coupler

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#958]
I added some new mapping files in config_grids.xml. I imported these files to the inputdata repository. Then, when I tried to run on a different machine, I got this message:

```
ERROR: File not found: lnd2glc_fmapname = "cpl/gridmaps/fv0.9x1.25/map_fv0.9x1.25_TO_gland4km_aave.161223.nc"
```

Running `check_input_data` from my case seems to indicate everything is present.

I think the problem is that `check_input_data` looks for files named `*.input_data_list`, but there is no such file for the coupler, so it appears that check_input_data doesn't detect (or download) this missing file.

**Comment by mvertens** [comment]
There is definitely a cpl.input_data_list created in all of the tests I
have been running. The problem is that lnd2glc_fmapname and
lnd2glc_smapname do not have an associated tag
of <input_pathname>abs</input_pathname>. This element is needed in the
entry block in order to have the mapping file appear in the
cpl.input_data_list.

As an example, atm2ocn_fmapname appears as:

  <entry id="atm2ocn_fmapname"    modify_via_xml="ATM2OCN_FMAPNAME">
    <type>char</type>
    <category>mapping</category>
    <input_pathname>abs</input_pathname>
    <group>seq_maps</group>
    <desc>
      atm to ocn flux mapping file for fluxes
    </desc>
    <values>
      <value>$ATM2OCN_FMAPNAME</value>
    </values>
  </entry>

And I see the following in the cpl.input_data_list
for ERS.T62_g16.C.yellowstone_intel.pop-default

atm2ocn_fmapname = /glade/p/cesmdata/cseg/inputdata/cpl/gridmaps/T62/
map_T62_TO_gx1v6_aave.130322.nc

However, the lnd2glc_fmapname appears as:

  <entry id="lnd2glc_fmapname"    modify_via_xml="LND2GLC_FMAPNAME">
    <type>char</type>
    <category>mapping</category>
    <input_pathname>abs</input_pathname>
    <group>seq_maps</group>
    <desc>
      land to glc mapping file for fluxes
    </desc>
    <values>
      <value>$LND2GLC_FMAPNAME</value>
    </values>

so the entry you are looking for is missing.

Could you try adding the appropriate <input_pathname>abs</input_pathname>
elements to the mapping files that do not have them and try again?

**Comment by billsacks** [comment]
I don't think that's the problem, unless I'm reading things wrong. You say that I need to add `<input_pathname>abs</input_pathname>`, but that already appears in the relevant sections. Quoting your reply (which I have confirmed myself):

```xml
  <entry id="lnd2glc_fmapname"    modify_via_xml="LND2GLC_FMAPNAME">
    <type>char</type>
    <category>mapping</category>
    <input_pathname>abs</input_pathname>
```

You're right, though, that cpl.input_data_list appears in successful runs. I'm thinking that the problem may be one of circular dependencies: It appears that `cpl.input_data_list` is written by the drv buildnml, and check_input_data only does its thing correctly if `cpl.input_data_list` is present. But if a necessary file isn't found, then the drv buildnml fails with an error like this:

```
ERROR: File not found: lnd2glc_fmapname = "cpl/gridmaps/fv0.9x1.25/map_fv0.9x1.25_TO_gland20km_aave.150514.nc"
```

and so never writes `cpl.input_data_list`.

Steps to reproduce:

1. Run `./create_test --test-root . --no-run SMS_D_Ly1.f09_g16_gl20.THISTG.yellowstone_gnu`. Notice that it creates a `cpl.input_data_list` file.

2. Temporarily move this file out of the way: `/glade/p/cesmdata/cseg/inputdata/cpl/gridmaps/fv0.9x1.25/map_fv0.9x1.25_TO_gland20km_aave.150514.nc`

3. Rerun the above test; notice that it now fails. You can run `./preview_namelists` to see what happens.

**Comment by billsacks** [comment]
@mvertens said she would fix this.
