### ISSUE TITLE
ERI test cases cannot be re-run

### ISSUE THREAD

**Issue by jgfouca** [ESMCI/cime#985]
```
./create_test ERI.f45_g37.X
* wait till completes *
cd $casedir
./case.submit
* wait till fails *
```

Error:  ERROR: (seq_infodata_Init) :: rpointer file read returns an error condition

**Comment by jgfouca** [comment]
Correction: It looks like ERR and ERS also do not work.

**Comment by jgfouca** [comment]
These additional problems were exposed when  #1014 was fixed.

**Comment by billsacks** [comment]
I'm reopening this, since it appears that the rerunnability of ERI has not actually been resolved. If we come to some broad agreement that this doesn't need to be rerun then we can close it as a WONTFIX, but until then I feel it should remain open.

My impression is that we used to have a requirement that all tests be rerunnable; again, if this requirement is dropped for some tests, then I feel that should be agreed upon by a broader group.

tagging @mvertens in case she has anything to add.

**Comment by jgfouca** [comment]
I'll take another look at it and see if it's really as hard as it looked.
